/*
 *  Copyright (C) 2012 Africa i-Parliaments
 * 
 *  This program is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU General Public License
 *  as published by the Free Software Foundation; either version 2
 *  of the License, or (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

/*
 * BungeniIntegrationPanel.java
 *
 * Created on Oct 23, 2012, 10:14:48 AM
 */

package org.bungeni.extpanels.bungeni;

import org.apache.log4j.Logger;
import org.bungeni.editor.panels.impl.BaseClassForITabbedPanel;

/**
 *
 * @author Ashok Hariharan
 */
public class BungeniIntegrationPanel extends BaseClassForITabbedPanel {
   private static org.apache.log4j.Logger log = Logger.getLogger(BungeniIntegrationPanel.class.getName());
    /** Creates new form BungeniIntegrationPanel */
    public BungeniIntegrationPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPaneBungeniDoc = new javax.swing.JTabbedPane();
        tabDocInfo = new javax.swing.JPanel();
        scrollInfo = new javax.swing.JScrollPane();
        txtTitle = new javax.swing.JTextArea();
        lblDocTitle = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        tabDocDesc = new javax.swing.JPanel();
        scrollDesc = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        lblTrasit = new javax.swing.JLabel();
        cboStatus = new javax.swing.JComboBox();
        scrollWorkingDocs = new javax.swing.JScrollPane();
        listWorkingDocs = new javax.swing.JList();
        lblWorkingDoc = new javax.swing.JLabel();
        btnImport = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnTransit = new javax.swing.JButton();

        tabPaneBungeniDoc.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N

        txtTitle.setColumns(20);
        txtTitle.setEditable(false);
        txtTitle.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        txtTitle.setRows(5);
        txtTitle.setWrapStyleWord(true);
        scrollInfo.setViewportView(txtTitle);

        lblDocTitle.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/bungeni/extpanels/bungeni/Bundle"); // NOI18N
        lblDocTitle.setText(bundle.getString("BungeniIntegrationPanel.lblDocTitle.text")); // NOI18N

        lblStatus.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        lblStatus.setText(bundle.getString("BungeniIntegrationPanel.lblStatus.text")); // NOI18N

        txtStatus.setEditable(false);
        txtStatus.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N

        javax.swing.GroupLayout tabDocInfoLayout = new javax.swing.GroupLayout(tabDocInfo);
        tabDocInfo.setLayout(tabDocInfoLayout);
        tabDocInfoLayout.setHorizontalGroup(
            tabDocInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDocInfoLayout.createSequentialGroup()
                .addGroup(tabDocInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDocTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabDocInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                    .addGroup(tabDocInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(tabDocInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(lblStatus))))
                .addContainerGap())
        );
        tabDocInfoLayout.setVerticalGroup(
            tabDocInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDocInfoLayout.createSequentialGroup()
                .addComponent(lblDocTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabPaneBungeniDoc.addTab(bundle.getString("BungeniIntegrationPanel.tabDocInfo.TabConstraints.tabTitle"), tabDocInfo); // NOI18N

        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        txtDescription.setRows(5);
        scrollDesc.setViewportView(txtDescription);

        javax.swing.GroupLayout tabDocDescLayout = new javax.swing.GroupLayout(tabDocDesc);
        tabDocDesc.setLayout(tabDocDescLayout);
        tabDocDescLayout.setHorizontalGroup(
            tabDocDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        tabDocDescLayout.setVerticalGroup(
            tabDocDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollDesc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tabPaneBungeniDoc.addTab(bundle.getString("BungeniIntegrationPanel.tabDocDesc.TabConstraints.tabTitle"), tabDocDesc); // NOI18N

        lblTrasit.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        lblTrasit.setText(bundle.getString("BungeniIntegrationPanel.lblTrasit.text")); // NOI18N

        cboStatus.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        cboStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        listWorkingDocs.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        listWorkingDocs.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrollWorkingDocs.setViewportView(listWorkingDocs);

        lblWorkingDoc.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        lblWorkingDoc.setText(bundle.getString("BungeniIntegrationPanel.lblWorkingDoc.text")); // NOI18N

        btnImport.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        btnImport.setText(bundle.getString("BungeniIntegrationPanel.btnImport.text")); // NOI18N
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        btnExport.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        btnExport.setText(bundle.getString("BungeniIntegrationPanel.btnExport.text")); // NOI18N
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        btnTransit.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        btnTransit.setText(bundle.getString("BungeniIntegrationPanel.btnTransit.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnImport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExport))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollWorkingDocs, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTransit))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblWorkingDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTrasit, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tabPaneBungeniDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tabPaneBungeniDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrasit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTransit)
                    .addComponent(cboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWorkingDoc)
                .addGap(11, 11, 11)
                .addComponent(scrollWorkingDocs, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImport)
                    .addComponent(btnExport))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImportActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnTransit;
    private javax.swing.JComboBox cboStatus;
    private javax.swing.JLabel lblDocTitle;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTrasit;
    private javax.swing.JLabel lblWorkingDoc;
    private javax.swing.JList listWorkingDocs;
    private javax.swing.JScrollPane scrollDesc;
    private javax.swing.JScrollPane scrollInfo;
    private javax.swing.JScrollPane scrollWorkingDocs;
    private javax.swing.JPanel tabDocDesc;
    private javax.swing.JPanel tabDocInfo;
    private javax.swing.JTabbedPane tabPaneBungeniDoc;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextArea txtTitle;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refreshPanel() {
       // do nothing
    }

}
