/*
 *  Copyright (C) 2012 PC
 * 
 *  This program is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU General Public License
 *  as published by the Free Software Foundation; either version 2
 *  of the License, or (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

/*
 * BungeniDocumentSourceSelectDocument.java
 *
 * Created on Oct 5, 2012, 5:27:30 PM
 */

package org.bungeni.editor.dialogs;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.concurrent.ExecutionException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.SwingWorker;
import org.apache.http.client.ResponseHandler;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.BasicResponseHandler;
import org.apache.http.impl.client.DefaultHttpClient;
import org.bungeni.editor.dialogs.BungeniDocumentSource.BungeniDocuments;

/**
 *
 * @author Ashok Hariharan
 */
public class BungeniDocumentSourceSelectDocument extends javax.swing.JPanel {

    private static org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(BungeniDocumentSourceSelectDocument.class.getName());



    private BungeniDocumentSource docSource = null;
    private JDialog parentDialog = null;
    /** Creates new form BungeniDocumentSourceSelectDocument */
    public BungeniDocumentSourceSelectDocument(JDialog parent) {
        initComponents();
        this.parentDialog = parent;
    }

    public void init(){

        this.docSource = new BungeniDocumentSource(
                "10.0.2.2",
                "8081",
                "login",
                "clerk.p1_01",
                "member"
                );
        this.cboSelectDocuments.setModel(
                new DefaultComboBoxModel(docSource.getBungeniDocuments().toArray())
                );
        this.cboSelectDocuments.addActionListener(cboSelectDocuments);
    }

    class cboSelectDocumentsListener implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            JComboBox cbox = (JComboBox)e.getSource();
            Object[] selections = cbox.getSelectedObjects();
            BungeniDocuments docsource = (BungeniDocuments) selections[0];
            openDocumentFromBungeni(docsource);
        }

    }


    class OpenDocumentWorker extends SwingWorker<String,Object> {

        BungeniDocuments bungeniDoc ;

        public OpenDocumentWorker(BungeniDocuments adoc){
            bungeniDoc = adoc;
        }

        @Override
        protected String doInBackground() throws Exception {
            String responseBody = "";
            if (docSource != null ) {
                DefaultHttpClient client = docSource.login();
                final HttpGet geturl = new HttpGet(bungeniDoc.url);
                ResponseHandler<String> responseHandler = new BasicResponseHandler();
                responseBody = client.execute(geturl, responseHandler);
            }
            return responseBody;
        }

        @Override
        public void done(){
            try {
                String sBody = get();
            } catch (InterruptedException ex) {
                log.error("Thread was interrupted", ex);
            } catch (ExecutionException ex) {
                log.error("Thread was interrupted", ex);
            }

        }

    }

    private void openDocumentFromBungeni(BungeniDocuments docsource) {

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboSelectDocuments = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        cboSelectDocuments.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Select Document");

        jButton2.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cboSelectDocuments, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cboSelectDocuments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboSelectDocuments;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables

}
