/*
 *  Copyright (C) 2012 PC
 * 
 *  This program is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU General Public License
 *  as published by the Free Software Foundation; either version 2
 *  of the License, or (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

/*
 * BungeniDocumentAttListPanel.java
 *
 * Created on Oct 12, 2012, 11:23:07 AM
 */

package org.bungeni.editor.dialogs;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import org.bungeni.extutils.BungeniDialog;
import org.jsoup.nodes.Element;

import org.jsoup.select.Elements;

/**
 *
 * @author PC
 */
public class BungeniDocumentAttListPanel extends javax.swing.JPanel {

    private BungeniDialog parentDialog = null;
    private Elements attlist = null;
    private List<Attachment> attachments = new ArrayList<Attachment>(0);
    private Attachment selectedAttachment = null;

    public class Attachment {
        public String title ;
        public String url ;
        public String downloadUrl;

        public Attachment () {
            title = "";
            url = "";
            downloadUrl = "";
        }
        public Attachment(String title, String url, String downloadUrl) {
            this.title = title;
            this.url = url;
            this.downloadUrl = downloadUrl;

        }

        @Override
        public String toString(){
            return this.title;
        }
    }

    /** Creates new form BungeniDocumentAttListPanel */
    public BungeniDocumentAttListPanel(BungeniDialog dlg, Elements attlist) {
        this.parentDialog = dlg;
        this.attlist = attlist;
        for (int i = 0; i < this.attlist.size(); i++) {
                Element elem = this.attlist.get(i);
                Attachment att = new Attachment();
                att.title = elem.text();
                att.url = elem.attr("href");
                att.downloadUrl = att.url + "/download";
                attachments.add(att);
        }
        initComponents();
        this.cboListAttachments.setModel (new DefaultComboBoxModel(attachments.toArray()));
        this.btnImportAttachment.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                selectedAttachment = (Attachment) cboListAttachments.getSelectedValue();
                parentDialog.dispose();
            }

        });
        this.btnCancel.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                parentDialog.dispose();
            }
            
        });
    }

    public Attachment getSelectedAttachment(){
        return this.selectedAttachment;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cboListAttachments = new javax.swing.JList();
        btnImportAttachment = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblDocInfo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        cboListAttachments.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(cboListAttachments);

        btnImportAttachment.setText("Import Attachment");

        btnCancel.setText("Cancel");

        lblDocInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDocInfo.setText("Document Information");

        jLabel1.setText("Kenya Information and Communications Bill  - [received by clerk]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnImportAttachment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDocInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDocInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImportAttachment)
                    .addComponent(btnCancel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void init(){
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnImportAttachment;
    private javax.swing.JList cboListAttachments;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDocInfo;
    // End of variables declaration//GEN-END:variables

}
