

package org.bungeni.editor.selectors.debaterecord.committees;

import com.sun.star.beans.PropertyValue;
import com.sun.star.beans.PropertyVetoException;
import com.sun.star.beans.UnknownPropertyException;
import com.sun.star.beans.XPropertySet;
import com.sun.star.container.XIndexAccess;
import com.sun.star.container.XIndexReplace;
import com.sun.star.lang.IllegalArgumentException;
import com.sun.star.lang.IndexOutOfBoundsException;
import com.sun.star.lang.WrappedTargetException;
import com.sun.star.style.NumberingType;
import com.sun.star.text.XParagraphCursor;
import com.sun.star.text.XText;
import com.sun.star.text.XTextCursor;
import com.sun.star.text.XTextRange;
import java.awt.Component;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.ResourceBundle;
import java.util.Vector;
import javax.swing.AbstractButton;
import javax.swing.table.DefaultTableModel;
import org.bungeni.db.BungeniClientDB;
import org.bungeni.db.BungeniRegistryFactory;
import org.bungeni.db.QueryResults;
import org.bungeni.editor.selectors.BaseMetadataPanel;
import org.bungeni.extutils.BungeniEditorProperties;
import org.bungeni.ooo.OOComponentHelper;
import org.bungeni.ooo.ooQueryInterface;

/**
 *
 * @author  undesa
 */
public class Committees extends BaseMetadataPanel {
  private static org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(Committees.class.getName());

    /** Creates new form TabledDocuments */
    public Committees() {
        super();
        initComponents();
        initTable();
    }
    private static final ResourceBundle bundle = ResourceBundle.getBundle("org/bungeni/editor/selectors/debaterecord/committees/Bundle");


    class TabledDocumentsModel extends DefaultTableModel {
        private boolean cellsEditable = false;

        public TabledDocumentsModel(){
            super();
        }

        @Override
        public boolean isCellEditable(int row, int col) {
            return cellsEditable;
        }

        public void setModelEditable(boolean bState) {
            this.cellsEditable = bState;
        }
    }

    protected String getTableQuery(){
        String countryIso = BungeniEditorProperties.getEditorProperty("countryISO");
        return new String("select committee_name, committee_uri from committees where country = '" +  countryIso + "'");
    }

    protected void initTable(){
        HashMap<String,String> registryMap = BungeniRegistryFactory.fullConnectionString();
            BungeniClientDB dbInstance = new BungeniClientDB(registryMap);
            dbInstance.Connect();
            QueryResults qr = dbInstance.QueryResults(getTableQuery());
            dbInstance.EndConnect();
            if (qr != null ) {
                if (qr.hasResults()) {
                    Vector<Vector<String>> resultRows = new Vector<Vector<String>>();
                    resultRows = qr.theResults();
                    TabledDocumentsModel mdl = new TabledDocumentsModel() ;
                    mdl.setDataVector(resultRows, qr.getColumnsAsVector());
                    tbl_Committees.setModel(mdl);
                     ((TabledDocumentsModel)this.tbl_Committees.getModel()).setModelEditable(false);
                     enableButtons(false);
                    }
            }
     }

    private void enableButtons(boolean b) {
        Enumeration<AbstractButton> buttons = this.grpEditButtons.getElements();
        while (buttons.hasMoreElements()) {
            AbstractButton abButton = buttons.nextElement();
            abButton.setEnabled(b);
        }
    }

        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpEditButtons = new javax.swing.ButtonGroup();
        lbl_SelectCommittee = new javax.swing.JLabel();
        scrollTabledDocs = new javax.swing.JScrollPane();
        tbl_Committees = new javax.swing.JTable();

        setName("Form"); // NOI18N

        lbl_SelectCommittee.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/bungeni/editor/selectors/debaterecord/committees/Bundle"); // NOI18N
        lbl_SelectCommittee.setText(bundle.getString("Committees.lbl_SelectCommittee.text")); // NOI18N
        lbl_SelectCommittee.setName("lbl_SelectCommittee"); // NOI18N

        scrollTabledDocs.setName("scrollTabledDocs"); // NOI18N

        tbl_Committees.setFont(new java.awt.Font("DejaVu Sans", 0, 11));
        tbl_Committees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Committees.setName("tbl_Committees"); // NOI18N
        scrollTabledDocs.setViewportView(tbl_Committees);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTabledDocs, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_SelectCommittee, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_SelectCommittee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTabledDocs, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.ButtonGroup grpEditButtons;
    private javax.swing.JLabel lbl_SelectCommittee;
    protected javax.swing.JScrollPane scrollTabledDocs;
    protected javax.swing.JTable tbl_Committees;
    // End of variables declaration//GEN-END:variables

    public String getPanelName() {
        return java.util.ResourceBundle.getBundle("org/bungeni/editor/selectors/debaterecord/committees/Bundle").getString("PanelName");
    }

    public Component getPanelComponent() {
        return this;
    }

      public HashMap<String,ArrayList<String>> getTableSelection() {

         int[] selectedRows = tbl_Committees.getSelectedRows();
         ArrayList<String> docTitles = new ArrayList<String>();
         ArrayList<String> docURIs = new ArrayList<String>();
             for (int i=0; i < selectedRows.length; i++) {
                 String docTitle = (String)tbl_Committees.getModel().getValueAt(i, 0 );
                 String docURI = (String) tbl_Committees.getModel().getValueAt(i, 1);
                 docTitles.add(docTitle);
                 docURIs.add(docURI);
             }
        HashMap<String,ArrayList<String>> tblData = new HashMap<String,ArrayList<String>>();
        tblData.put("document_titles", docTitles);
        tblData.put("document_uris", docURIs);
        return tblData;
    
      }
        
        
    @Override
    public boolean preFullEdit() {
        return true;
    }

    @Override
    public boolean processFullEdit() {
        return true;
    }

    @Override
    public boolean postFullEdit() {
        return true;
    }

    @Override
    public boolean preFullInsert() {
        return true;
    }

    @Override
    public boolean processFullInsert() {
        return true;
    }

    @Override
    public boolean postFullInsert() {
        return true;
    }

    @Override
    public boolean preSelectEdit() {
        return true;
    }

    @Override
    public boolean processSelectEdit() {
        return true;
    }

    @Override
    public boolean postSelectEdit() {
        return true;
    }

   
   
    
    @Override
    public boolean preSelectInsert() {
        HashMap<String,ArrayList<String>> tblData = new HashMap<String,ArrayList<String>>();
        
        
        return true;
    }

    @Override
    public boolean processSelectInsert() {
        // applyBulletedList();
        return true;
    }

    @Override
    public boolean postSelectInsert() {
        return true;
    }

    @Override
    public boolean validateSelectedEdit() {
        return true;
    }

    @Override
    public boolean validateSelectedInsert() {
        //validate the tabled documents
        //all rows in table need to be full.
        boolean bState = true;

        if (this.tbl_Committees.getSelectedRowCount() == 0) {
            addErrorMessage(this.tbl_Committees, bundle.getString("no_row_selected"));
            bState = false;
        }  else {
            //validate selected rows for empty data
            int[] nRows = this.tbl_Committees.getSelectedRows();
            int nCols = this.tbl_Committees.getColumnCount();

            for (int i = 0; i < nRows.length; i++) {
                for (int j = 0; j < nCols; j++) {
                   String sValue = (String) this.tbl_Committees.getValueAt(nRows[i], j);
                   if (sValue.trim().length() == 0) {
                       Object[] values = {Integer.toString(nRows[i]+1), Integer.toString(j+1)};
                       String formattedMsg = MessageFormat.format(bundle.getString("tableValidationError"),
                               values);
                       this.addErrorMessage(this.tbl_Committees, formattedMsg);
                       bState = false;
                   }
                }
            }
        }


  
        return bState;
    }

    @Override
    public boolean validateFullInsert() {
        return true;
    }

    @Override
    public boolean validateFullEdit() {
        return true;
    }

    @Override
    public boolean doCancel() {
        return true;
    }

    @Override
    public boolean doReset() {
        return true;
    }
    @Override
    protected void initFieldsSelectedEdit() {
        return;
    }

    @Override
    protected void initFieldsSelectedInsert() {
      //  BungeniClientDB dbnew = new BungeniClientDB();
        return;
    }

    @Override
    protected void initFieldsInsert() {
        return;
    }

    @Override
    protected void initFieldsEdit() {
        return;
    }
}
