/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * panelStructuralError.java
 *
 * Created on Mar 25, 2009, 2:58:59 PM
 */

package org.bungeni.editor.rules.ui;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import org.bungeni.editor.rulesimpl.StructuralError;
import org.bungeni.editor.rulesimpl.StructuralErrorMessage;

/**
 *
 * @author undesa
 */
public class panelStructuralError extends javax.swing.JPanel {
    ArrayList<StructuralError> structuralErrors = new ArrayList<StructuralError>(0);
    /** Creates new form panelStructuralError */
    public panelStructuralError(ArrayList<StructuralError> serror) {
        this.structuralErrors = serror;
        initComponents();
        initTable();
    }

    private void initTable(){
        //build vectors for table model
        Vector<String> vColumns = new Vector<String>();
        vColumns.add("No.");
        vColumns.add("Error");
        Vector<Vector<String>> vData = new Vector<Vector<String>>();
        Integer n = 1;
        for (StructuralError ee : structuralErrors) {
            Vector<String> vRow = new Vector<String>();
            String msg = StructuralErrorMessage.toErrorMessage(ee);
            vRow.add(n.toString());
            vRow.add(msg);
            vData.add(vRow);
            n++;
        }
        //set table model
        DefaultTableModel dtm = new DefaultTableModel(vData, vColumns);
        this.tblErrors = new JTable() {
                @Override
                 public boolean isCellEditable(int rowIndex, int vColIndex) {
                    return false;
                    }
             };
             tblErrors.setModel(dtm);
             tblErrors.setRowSelectionAllowed(true);
             tblErrors.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
             this.scrollTblErrors.add(tblErrors);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollTblErrors = new javax.swing.JScrollPane();
        tblErrors = new javax.swing.JTable();

        tblErrors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollTblErrors.setViewportView(tblErrors);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTblErrors, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTblErrors, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollTblErrors;
    private javax.swing.JTable tblErrors;
    // End of variables declaration//GEN-END:variables

}
