<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"
	xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0"
	xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0"
	xmlns:table="urn:oasis:names:tc:opendocument:xmlns:table:1.0"
	xmlns:draw="urn:oasis:names:tc:opendocument:xmlns:drawing:1.0"
	xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0"
	xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:meta="urn:oasis:names:tc:opendocument:xmlns:meta:1.0"
	xmlns:number="urn:oasis:names:tc:opendocument:xmlns:datastyle:1.0"
	xmlns:svg="urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0"
	xmlns:chart="urn:oasis:names:tc:opendocument:xmlns:chart:1.0"
	xmlns:dr3d="urn:oasis:names:tc:opendocument:xmlns:dr3d:1.0"
	xmlns:math="http://www.w3.org/1998/Math/MathML"
	xmlns:form="urn:oasis:names:tc:opendocument:xmlns:form:1.0"
	xmlns:script="urn:oasis:names:tc:opendocument:xmlns:script:1.0"
	xmlns:ooo="http://openoffice.org/2004/office" xmlns:ooow="http://openoffice.org/2004/writer"
	xmlns:oooc="http://openoffice.org/2004/calc" xmlns:dom="http://www.w3.org/2001/xml-events"
	xmlns:xforms="http://www.w3.org/2002/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:saxon="http://saxon.sf.net/"
        xmlns:field="urn:openoffice:names:experimental:ooo-ms-interop:xmlns:field:1.0"
        xmlns:rpt="http://openoffice.org/2005/report"
        xmlns:anx="http://anx.akomantoso.org/1.0"
        xmlns:of="urn:oasis:names:tc:opendocument:xmlns:of:1.2"
        xmlns:rdfa="http://docs.oasis-open.org/opendocument/meta/rdfa#"
        xmlns:bungeni="http://editor.bungeni.org/1.0/anx/" 
	exclude-result-prefixes="xsl xsd xsi text office style table draw fo xlink dc meta number svg chart dr3d math form script ooo ooow oooc dom xforms field rpt rdfa of anx"
	extension-element-prefixes="saxon" version="2.0">
	<xsl:output indent="yes" method="xml"/>

	<xsl:template match="/">
		<xsl:apply-templates/>
	</xsl:template>

	<xsl:template match="*">
		<xsl:if test="not(preceding-sibling::node()/@id = current()/@id)">
			<xsl:element name="{name()}">
				<xsl:for-each select="@*">
					<xsl:attribute name="{local-name(.)}">
						<xsl:value-of select="."/>
					</xsl:attribute>
				</xsl:for-each>
				<xsl:apply-templates/>
			</xsl:element>
		</xsl:if>
	</xsl:template> 
	
	<xsl:template match="root" >
		<xsl:element name="{name()}" inherit-namespaces="yes" >
			<xsl:for-each select="@*">
				<xsl:attribute name="{local-name(.)}">
					<xsl:value-of select="."/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:apply-templates select="*[@name != 'meta']"/>
		</xsl:element>
	</xsl:template>

	<xsl:template match="container[@name = 'body']">
		<container>
		   
			<xsl:for-each select="@*">
				<xsl:attribute name="{local-name(.)}">
					<xsl:value-of select="."/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:apply-templates select="//mcontainer[@name = 'meta']"/>
			<xsl:apply-templates select="*[@name != 'meta']"/>
		</container>
	</xsl:template>

	<xsl:template match="block[count(node()) = 0]">
		<xsl:apply-templates/>
	</xsl:template>

	<xsl:template match="block[./parent::container[@name='list']]">
		<container name="item" id="{generate-id(.)}">
			<xsl:copy-of select="."/>
		</container>
	</xsl:template>

	<xsl:template match="inline[count(node()) = 0]">
		<xsl:apply-templates/>
	</xsl:template>


	<!-- TO BE FIXED IN THE INPUT -->
	<!--<xsl:template match="block[@id='d3e1060']">
	    <container name="speech" id="{generate-id(.)}" class="autoGenerated">
	        <xsl:copy-of select="." />
	    </container>
	</xsl:template> -->

	<xsl:template match="ref">
		<inline name="ref">
			<xsl:attribute name="class" select="tokenize(@name,':')[position()=1]"/>
			<xsl:attribute name="href"
				select="if (tokenize(@name,':')[position()=2]) then tokenize(@name,':')[position()=2] else @href"/>
			<xsl:attribute name="id" select="generate-id(.)"/>
			<xsl:apply-templates/>
		</inline>
	</xsl:template>

	<xsl:template match="container[./child::htitle]">
		<hcontainer>
			<xsl:for-each select="@*">
				<xsl:attribute name="{local-name(.)}">
					<xsl:value-of select="."/>
				</xsl:attribute>
			</xsl:for-each>
			<xsl:apply-templates/>
		</hcontainer>
	</xsl:template>

	<xsl:template match="container[./child::htitle]/block[count(node()) != 0]">
		<container>
			<xsl:attribute name="id" select="generate-id(.)"/>
			<xsl:attribute name="name">fixing_hcontainer</xsl:attribute>
			<block>
				<xsl:for-each select="@*">
					<xsl:attribute name="{local-name(.)}">
						<xsl:value-of select="."/>
					</xsl:attribute>
				</xsl:for-each>
				<xsl:apply-templates/>
			</block>
		</container>
	</xsl:template>

	<!-- REMOVE DUPLICATED META -->
 
</xsl:stylesheet>
