/*
 * floatingSectionMetadataPanel.java
 *
 * Created on November 19, 2008, 9:10 PM
 */

package org.bungeni.editor.panels;

import java.awt.Component;
import java.awt.Font;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JFrame;
import javax.swing.Timer;
import org.bungeni.editor.actions.EditorActionFactory;
import org.bungeni.editor.actions.IEditorActionEvent;
import org.bungeni.editor.actions.toolbarAction;
import org.bungeni.editor.dialogs.metadatapanel.SectionMetadataLoad;
import org.bungeni.editor.panels.impl.IFloatingPanel;
import org.bungeni.ooo.OOComponentHelper;

/**
 *
 * @author  undesa
 */
public class floatingSectionMetadataPanel extends javax.swing.JPanel implements IFloatingPanel {
    private OOComponentHelper ooDocument;
    private JFrame parentFrame;
    private Timer refreshTimer;
    private Action sectionViewRefreshRunner;
    
    /** Creates new form floatingSectionMetadataPanel */
    public floatingSectionMetadataPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDisplaySectionName = new javax.swing.JLabel();
        lblSecName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnHide = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSectionmeta = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray));
        setFont(new java.awt.Font("DejaVu Sans", 0, 9));

        lblDisplaySectionName.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        lblDisplaySectionName.setText("::");

        lblSecName.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        lblSecName.setText("Current Section Name :");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        jLabel3.setText("::");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        jLabel4.setText("Current Section Type:");

        btnEdit.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        btnEdit.setText("Edit ");
        btnEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnHide.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        btnHide.setText("Hide");
        btnHide.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jToggleButton1.setFont(new java.awt.Font("DejaVu Sans", 0, 9));
        jToggleButton1.setText("EXPAND");
        jToggleButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tblSectionmeta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSectionmeta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSecName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDisplaySectionName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHide, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblSecName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDisplaySectionName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(btnEdit)
                    .addComponent(btnHide))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHide;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblDisplaySectionName;
    private javax.swing.JLabel lblSecName;
    private javax.swing.JTable tblSectionmeta;
    // End of variables declaration//GEN-END:variables

    public void setOOComponentHandle(OOComponentHelper ooComponent) {
        ooDocument = ooComponent;
    }

    public Component getObjectHandle() {
        return this;
    }

    public IEditorActionEvent getEventClass(toolbarAction action) {
        IEditorActionEvent event = EditorActionFactory.getEventClass(action);
        return event;
    }

    public void setParentWindowHandle(JFrame c) {
        parentFrame = c;
    }

    public JFrame getParentWindowHandle() {
        return parentFrame;
    }

    public void initUI() {
       initTimers();
    }

    public void updateSectionMetadataView(String sectionName) {
          this.lblDisplaySectionName.setText(sectionName);
          SectionMetadataLoad sectionMetadataTableModel = new SectionMetadataLoad(ooDocument,sectionName);
          this.tblSectionmeta.setModel(sectionMetadataTableModel);
          this.tblSectionmeta.setFont(new Font("Tahoma", Font.PLAIN, 11)); 
    }
    
    private void initTimers(){
       sectionViewRefreshRunner = new viewRefreshAction();
        refreshTimer = new Timer(3000, sectionViewRefreshRunner);
        refreshTimer.setInitialDelay(2000);
        refreshTimer.start();
    }

    public void setSectionChangeInfo(String sectionChange) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    private class viewRefreshAction extends AbstractAction {
        public String oldSectionName ; 
        public String newSectionName;
        public void actionPerformed(ActionEvent arg0) {
            if (ooDocument != null ) {
                String sSect = ooDocument.currentSectionName();
                if (sSect != null) {
                    newSectionName = sSect;
                    if (newSectionName.equals(oldSectionName)) {
                        //dont do anything
                    } else {
                        updateSectionMetadataView(newSectionName);
                        oldSectionName = newSectionName;
                    }
                }
            }
        }
    }
}
