/*
 * documentMetadataPanel.java
 *
 * Created on May 15, 2008, 11:47 AM
 */

package org.bungeni.editor.panels;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTree;
import javax.swing.Timer;
import javax.swing.tree.TreeCellRenderer;
import org.bungeni.extutils.BungeniEditorPropertiesHelper;
import org.bungeni.editor.dialogs.treetable.DocMetadataTreeTableModel;
import org.bungeni.editor.dialogs.treetable.sectionHive;
import org.bungeni.editor.metadata.DocumentMetadataTableModel;
import org.bungeni.ooo.OOComponentHelper;
import org.jdesktop.swingx.JXTreeTable;

/**
 *
 * @author  Administrator
 */
public class sectionMetadataPanel extends javax.swing.JPanel {
    private OOComponentHelper ooDocument;
    private JFrame parentFrame;
    private DocMetadataTreeTableModel docMetadataTreeTableModel;
    private Timer sectionMetadataRefreshTimer;
    /** Creates new form documentMetadataPanel */
    public sectionMetadataPanel() {
        initComponents();
    }
    
   public sectionMetadataPanel(OOComponentHelper ooDocument, JFrame parentFrame){
         this.parentFrame=parentFrame;
         this.ooDocument=ooDocument;
         init();
     }
    
    private void init() {
        initComponents();
        initTreeTableDocumentMetadata();    
        initTimer();
    }
    
    private  void initTimer(){
          sectionMetadataRefreshTimer= new Timer(4000, new ActionListener() {
              public void actionPerformed(ActionEvent e) {
                refreshSectionMetadataTreeTable();
              }
           });
           sectionMetadataRefreshTimer.start();
    }

    private void refreshSectionMetadataTreeTable(){
        //
   
        docMetadataTreeTableModel.refreshModel();
        this.treeTableDocumentMetadata.expandAll();
    }
    
    private void initTreeTableDocumentMetadata() {
        sectionHive rootHive = new sectionHive(BungeniEditorPropertiesHelper.getDocumentRoot());
        docMetadataTreeTableModel = new DocMetadataTreeTableModel(ooDocument, rootHive);
        treeTableDocumentMetadata.setTreeTableModel(docMetadataTreeTableModel);
        treeTableDocumentMetadata.setTreeCellRenderer(new treeTableDocumentMetadataCellRenderer());
    }
    
    public class treeTableDocumentMetadataCellRenderer extends JLabel implements TreeCellRenderer
    {
       
        
    public Component getTreeCellRendererComponent(JTree tree, Object value, boolean selected, boolean expanded, boolean leaf, int row, boolean hasFocus)
    {
        setForeground(Color.BLACK);
        setBorder(new javax.swing.border.LineBorder(Color.GRAY, 1));
        if(docMetadataTreeTableModel.getValueAt(value, 1).equals("")){
            setToolTipText(value.toString());
          }else{
              setToolTipText(value.toString() + ":" + docMetadataTreeTableModel.getValueAt(value, 1));
          }
         if (selected){
                    Component vRenderPane = tree.getParent();
                    if (vRenderPane != null){
                            JXTreeTable vTable = (JXTreeTable)vRenderPane.getParent();
                            if (vTable != null){
                                    if (vTable.hasFocus()){
                                            setForeground(Color.WHITE);
                                    }
                            }
                    }
            }
            setText(value.toString());
            return this;
    }
    
    
    
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        lblDescDocMetadata = new javax.swing.JLabel();
        scrollPaneTreeTableDocumentMetadata = new javax.swing.JScrollPane();
        treeTableDocumentMetadata = new org.jdesktop.swingx.JXTreeTable();

        getAccessibleContext().setAccessibleDescription("Section Metadata");
        lblDescDocMetadata.setText("Section Metadata");

        scrollPaneTreeTableDocumentMetadata.setViewportView(treeTableDocumentMetadata);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblDescDocMetadata, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 196, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(scrollPaneTreeTableDocumentMetadata, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(lblDescDocMetadata)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(scrollPaneTreeTableDocumentMetadata, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 277, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDescDocMetadata;
    private javax.swing.JScrollPane scrollPaneTreeTableDocumentMetadata;
    private org.jdesktop.swingx.JXTreeTable treeTableDocumentMetadata;
    // End of variables declaration//GEN-END:variables
    
}
