/*
 * templatePanel.java
 *
 * Created on August 16, 2007, 4:22 PM
 */

package org.bungeni.editor.panels;

import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author  Administrator
 */
public class templatePanel extends javax.swing.JPanel {
    private static org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(templatePanel.class.getName());
  
    /** Creates new form templatePanel */
    public templatePanel() {
        //initComponents();
    }
    
     protected JButton createButton(String imageName, String actionCommand, String tooltipText, String altText){
           String imgLocation = "/gui/"
                             + imageName
                             + ".png";
            URL imageURL = templatePanel.class.getResource(imgLocation);
        //Create and initialize the button.
        JButton button = new JButton();
        button.setActionCommand(actionCommand);
        button.setToolTipText(tooltipText);
        
        if (imageURL != null) {                      //image found
            button.setIcon(new ImageIcon(imageURL, altText));
        } else {                                     //no image found
            button.setText(altText);
           log.debug("Resource not found: "
                               + imgLocation);
        }
        return button;
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
