/*
 * panelTrackChanges.java
 *
 * Created on March 9, 2009, 10:21 AM
 */

package org.bungeni.trackchanges;

import java.io.File;
import java.io.FilenameFilter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractListModel;
import org.bungeni.odfdocument.docinfo.BungeniChangeDocumentsInfo;
import org.bungeni.odfdom.document.BungeniOdfDocumentHelper;
import org.odftoolkit.odfdom.doc.OdfDocument;

/**
 *
 * @author  undesa
 */
public class panelTrackChanges extends javax.swing.JPanel {

    String __TEST_FOLDER__ = "";
    BungeniChangeDocumentsInfo changesInfo = new BungeniChangeDocumentsInfo();

    /** Creates new form panelTrackChanges */
    public panelTrackChanges() {
        initComponents();
        __TEST_FOLDER__ ="/Users/ashok/Devel/TrackChanges/netbeansProject/Files";
        loadFilesFromFolder();
        initialize();
    }

    /**
     * Initialize controls with data
     */
    private void initialize() {
        listMembers.setModel(new DocOwnerListModel());
    }

    /**
     * Loads change files from folder
     */
    private void loadFilesFromFolder() {
        File fFolder = new File(__TEST_FOLDER__);
        //find files in changes folder
        if (fFolder.isDirectory()) {
           File[] files =  fFolder.listFiles(new FilenameFilter(){
                public boolean accept(File dir, String name) {
                    if (name.startsWith("doc_")){
                        return true;
                    }
                    return false;
                }

            });

            //load files from folder
            for (int i = 0; i < files.length ; i++ ) {
                OdfDocument oDoc = null;
                try {

                    BungeniOdfDocumentHelper docHelper = new BungeniOdfDocumentHelper(files[i]);
                    changesInfo.addDocument(docHelper);

                } catch (Exception ex) {
                    Logger.getLogger(panelTrackChanges.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }

 

    /**
     * List model for document owner
     */
    private class DocOwnerListModel extends AbstractListModel {

        public int getSize() {
          return changesInfo.getSize();
        }

        public Object getElementAt(int arg0) {
            BungeniOdfDocumentHelper docHelper =  changesInfo.getDocuments().get(arg0);
            return docHelper.getPropertiesHelper().getUserDefinedPropertyValue("BungeniDocOwner");
        }



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMembers = new javax.swing.JLabel();
        scrollMembers = new javax.swing.JScrollPane();
        listMembers = new javax.swing.JList();
        scrollDocInfo = new javax.swing.JScrollPane();
        txtareaDocInfo = new javax.swing.JTextArea();
        lblDocInfo = new javax.swing.JLabel();
        scrollDocChanges = new javax.swing.JScrollPane();
        tblDocChanges = new javax.swing.JTable();
        btnViewDoc = new javax.swing.JButton();
        btnViewOrigDoc = new javax.swing.JButton();
        btnApplyChanges = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        lblMembers.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        lblMembers.setText("Changes by User");

        listMembers.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Tinoula Awopetu", "Mashinski Murigi", "Raul Obwacha", "Felix Kerstengor" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrollMembers.setViewportView(listMembers);

        txtareaDocInfo.setColumns(20);
        txtareaDocInfo.setEditable(false);
        txtareaDocInfo.setRows(5);
        scrollDocInfo.setViewportView(txtareaDocInfo);

        lblDocInfo.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        lblDocInfo.setText("Document Info");

        tblDocChanges.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Delete", "23/12", "P(3)/L(4)", "This is an exceptional rule", null},
                {"Insert", "23/12", "P(5)/L(6)", ", for eternity.", new Boolean(true)},
                {"Delete", "23/12", "P(8)/W(23)", "The rule of law", new Boolean(true)}
            },
            new String [] {
                "Action", "Date", "Position", "Text", "Accept / Reject"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollDocChanges.setViewportView(tblDocChanges);

        btnViewDoc.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        btnViewDoc.setText("View Document");

        btnViewOrigDoc.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        btnViewOrigDoc.setText("View Original Document");

        btnApplyChanges.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        btnApplyChanges.setText("Apply Changes");

        btnCancel.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        btnCancel.setText("Cancel");

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        jLabel1.setText("Document Changes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDocInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(scrollDocInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(scrollMembers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(lblMembers, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scrollDocChanges, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btnViewDoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewOrigDoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnApplyChanges)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMembers)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollMembers, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDocInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollDocInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                    .addComponent(scrollDocChanges, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewDoc)
                    .addComponent(btnViewOrigDoc)
                    .addComponent(btnApplyChanges)
                    .addComponent(btnCancel))
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyChanges;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnViewDoc;
    private javax.swing.JButton btnViewOrigDoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDocInfo;
    private javax.swing.JLabel lblMembers;
    private javax.swing.JList listMembers;
    private javax.swing.JScrollPane scrollDocChanges;
    private javax.swing.JScrollPane scrollDocInfo;
    private javax.swing.JScrollPane scrollMembers;
    private javax.swing.JTable tblDocChanges;
    private javax.swing.JTextArea txtareaDocInfo;
    // End of variables declaration//GEN-END:variables

}
