/*
 * DebateRecordMetadata.java
 *
 * Created on November 4, 2008, 1:43 PM
 */

package org.bungeni.editor.metadata.editors;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import org.bungeni.extutils.BungeniEditorProperties;
import org.bungeni.editor.metadata.BaseEditorDocMetadataDialog;
import org.bungeni.editor.metadata.BillMetaModel;
import org.bungeni.editor.selectors.SelectorDialogModes;
import org.bungeni.utils.BungeniFileSavePathFormat;
import org.bungeni.extutils.CommonStringFunctions;

/**
 *
 * @author  undesa
 */
public class BillMetadata extends BaseEditorDocMetadataDialog {

    private static org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(BillMetadata.class.getName());
    BillMetaModel docMetaModel = new BillMetaModel();
     
    
 //   OOComponentHelper ooDocument  = null;
 //   JFrame parentFrame = null;
 //    SelectorDialogModes dlgMode = null;
    
    
    public BillMetadata(){
        super();
        initComponents();
    }
    
    @Override
    public void initialize() {
        super.initialize();
        
        this.docMetaModel.setup();
        initControls();
           if (theMode == SelectorDialogModes.TEXT_EDIT) {
            try {
                //retrieve metadata... and set in controls....
                docMetaModel.loadModel(ooDocument);
  
               String sBillNo = docMetaModel.getItem("BungeniBillNo");
                String sBillName = docMetaModel.getItem("BungeniBillName");
                String sAssentDate = docMetaModel.getItem("BungeniDateOfAssent");
                String sCommencementDate = docMetaModel.getItem("BungeniDateOfCommencement");
                SimpleDateFormat formatter = new SimpleDateFormat(BungeniEditorProperties.getEditorProperty("metadataDateFormat"));
                //official date
                if (!CommonStringFunctions.emptyOrNull(sAssentDate)) {
                this.dt_dateofassent.setDate(formatter.parse(sAssentDate));
                }
                //official time
                if (!CommonStringFunctions.emptyOrNull(sCommencementDate) ) {
                    SimpleDateFormat timeFormat = new SimpleDateFormat(BungeniEditorProperties.getEditorProperty("metadataTimeFormat"));
                    this.dt_dateofcommencement.setDate(timeFormat.parse(sCommencementDate));
                }
                if (!CommonStringFunctions.emptyOrNull(sBillNo))
                    this.txtBillNumber.setText(sBillNo);
                if (!CommonStringFunctions.emptyOrNull(sBillName))
                    this.txtBillName.setText(sBillName);
            } catch (ParseException ex) {
                log.error("initalize()  =  "  + ex.getMessage());
            }
         
        }
    }

    public Component getPanelComponent() {
        return this;
    }
    
    private void initControls(){
        String popupDlgBackColor = BungeniEditorProperties.getEditorProperty("popupDialogBackColor");
        this.setBackground(Color.decode(popupDlgBackColor));
    }
    

public boolean applySelectedMetadata(BungeniFileSavePathFormat spf){
    boolean bState = false;
    try {
    String sBillNo = this.txtBillNumber.getText();
    String sBillName = this.txtBillName.getText();
    //get the assent date
       SimpleDateFormat dformatter = new SimpleDateFormat (BungeniEditorProperties.getEditorProperty("metadataDateFormat"));
       final String strDateOfAssent = dformatter.format( this.dt_dateofassent.getDate());
       final String strDateOfCommencement = dformatter.format(this.dt_dateofcommencement.getDate());
       // docMetaModel.updateItem("BungeniParliamentID")
        docMetaModel.updateItem("BungeniBillNo", sBillNo);
        docMetaModel.updateItem("BungeniBillName", sBillName);
        docMetaModel.updateItem("BungeniDateOfAssent", strDateOfAssent);
        docMetaModel.updateItem("BungeniDateOfCommencement", strDateOfCommencement);
        docMetaModel.saveModel(ooDocument);
    bState = true;
    } catch (Exception ex) {
        log.error("applySelectedMetadata : " + ex.getMessage());
        bState = false;
    } finally {
        return bState;
    }
}    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBillNumber = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtBillName = new javax.swing.JTextField();
        lblBillName = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dt_dateofassent = new org.jdesktop.swingx.JXDatePicker();
        jLabel13 = new javax.swing.JLabel();
        dt_dateofcommencement = new org.jdesktop.swingx.JXDatePicker();

        txtBillNumber.setFont(new java.awt.Font("DejaVu Sans", 0, 10));

        jLabel11.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        jLabel11.setText("Bill Number");

        txtBillName.setFont(new java.awt.Font("DejaVu Sans", 0, 10));

        lblBillName.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        lblBillName.setText("Bill Name");

        jLabel12.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        jLabel12.setText("Date of Assent");
        jLabel12.setName("lbl.BungeniParliamentSitting"); // NOI18N

        dt_dateofassent.setFont(new java.awt.Font("DejaVu Sans", 0, 10));

        jLabel13.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        jLabel13.setText("Date of Commencement");
        jLabel13.setName("lbl.BungeniParliamentSitting"); // NOI18N

        dt_dateofcommencement.setFont(new java.awt.Font("DejaVu Sans", 0, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addComponent(lblBillName)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBillName)
                    .addComponent(txtBillNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(dt_dateofassent, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(dt_dateofcommencement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBillNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBillName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBillName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dt_dateofassent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dt_dateofcommencement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker dt_dateofassent;
    private org.jdesktop.swingx.JXDatePicker dt_dateofcommencement;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel lblBillName;
    private javax.swing.JTextField txtBillName;
    private javax.swing.JTextField txtBillNumber;
    // End of variables declaration//GEN-END:variables


    @Override
    public Dimension getFrameSize() {
        int DIM_X = 229 ; int DIM_Y = 222 ;
        return new Dimension(DIM_X, DIM_Y + 10);
    }

   


   


}
