/*
 * DebateRecordMetadata.java
 *
 * Created on November 4, 2008, 1:43 PM
 */

package org.bungeni.editor.metadata.editors;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.Date;
import org.bungeni.utils.BungeniEditorProperties;
import org.bungeni.editor.metadata.BaseEditorDocMetadataDialog;
import org.bungeni.editor.metadata.JudgementMetadataModel;
import org.bungeni.editor.selectors.SelectorDialogModes;
import org.bungeni.utils.BungeniFileSavePathFormat;
import org.bungeni.utils.CommonStringFunctions;

/**
 *
 * @author  undesa
 */
public class JudgementMetadata extends BaseEditorDocMetadataDialog {

    private static org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(JudgementMetadata.class.getName());
    JudgementMetadataModel docMetaModel = new JudgementMetadataModel();
     
    
 //   OOComponentHelper ooDocument  = null;
 //   JFrame parentFrame = null;
 //    SelectorDialogModes dlgMode = null;
    
    
    public JudgementMetadata(){
        super();
        initComponents();
    }
    
    @Override
    public void initialize() {
        super.initialize();
        
        this.docMetaModel.setup();
        initControls();
           if (theMode == SelectorDialogModes.TEXT_EDIT) {
            try {
                //retrieve metadata... and set in controls....
                docMetaModel.loadModel(ooDocument);
  
               String sJudgementNo = docMetaModel.getItem("BungeniJudgementNo");
                String sCaseNo = docMetaModel.getItem("BungeniCaseNo");
                String sJudgementDate = docMetaModel.getItem("BungeniJudgementDate");
                if (!CommonStringFunctions.emptyOrNull(sJudgementNo))
                    this.txtJudgementNo.setText(sJudgementNo);
                if (!CommonStringFunctions.emptyOrNull(sCaseNo))
                    this.txtCaseNo.setText(sCaseNo);
                 if (!CommonStringFunctions.emptyOrNull(sJudgementDate)) {
                    this.dt_judgement_date.setDate(sdfDateFormat.parse(sJudgementDate));
                }
            } catch (Exception ex) {
                log.error("initalize()  =  "  + ex.getMessage());
            }
         
        }
    }

    public Component getPanelComponent() {
        return this;
    }
    
    private void initControls(){
        String popupDlgBackColor = BungeniEditorProperties.getEditorProperty("popupDialogBackColor");
        this.setBackground(Color.decode(popupDlgBackColor));
    }
    

public boolean applySelectedMetadata(BungeniFileSavePathFormat spf){
    boolean bState = false;
    try {
    String sJudgementNo = this.txtJudgementNo.getText();
    String sCaseNo = this.txtCaseNo.getText();
    Date dJudgementDate = this.dt_judgement_date.getDate();
    String sJudgementDate = this.sdfDateFormat.format(dJudgementDate);
    //get the assent date
       // docMetaModel.updateItem("BungeniParliamentID")
        docMetaModel.updateItem("BungeniJudgementNo", sJudgementNo);
        docMetaModel.updateItem("BungeniCaseNo", sCaseNo);
        docMetaModel.updateItem("BungeniJudgementDate", sJudgementDate);
        docMetaModel.saveModel(ooDocument);
    bState = true;
    } catch (Exception ex) {
        log.error("applySelectedMetadata : " + ex.getMessage());
        bState = false;
    } finally {
        return bState;
    }
}    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtJudgementNo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCaseNo = new javax.swing.JTextField();
        lblBillName = new javax.swing.JLabel();
        dt_judgement_date = new org.jdesktop.swingx.JXDatePicker();
        lblBillName1 = new javax.swing.JLabel();

        setBackground(java.awt.Color.lightGray);

        txtJudgementNo.setFont(new java.awt.Font("DejaVu Sans", 0, 10));

        jLabel11.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        jLabel11.setText("Judgement No.");

        txtCaseNo.setFont(new java.awt.Font("DejaVu Sans", 0, 10));

        lblBillName.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        lblBillName.setText("Case No.");

        dt_judgement_date.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N

        lblBillName1.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        lblBillName1.setText("Judgement Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBillName1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(dt_judgement_date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblBillName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtJudgementNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                        .addComponent(txtCaseNo)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJudgementNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBillName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCaseNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lblBillName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dt_judgement_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker dt_judgement_date;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel lblBillName;
    private javax.swing.JLabel lblBillName1;
    private javax.swing.JTextField txtCaseNo;
    private javax.swing.JTextField txtJudgementNo;
    // End of variables declaration//GEN-END:variables


    @Override
    public Dimension getFrameSize() {
        int DIM_X = 229 ; int DIM_Y = 222 ;
        return new Dimension(DIM_X, DIM_Y + 10);
    }

   


   


}
