/*
 * DebateRecordMetadata.java
 *
 * Created on November 4, 2008, 1:43 PM
 */

package org.bungeni.editor.metadata.editors;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import org.bungeni.db.registryQueryDialog2;
import org.bungeni.ooo.ooDocMetadataFieldSet;
import org.bungeni.utils.BungeniEditorProperties;
import org.bungeni.editor.metadata.BaseEditorDocMetadataDialog;
import org.bungeni.editor.metadata.JudgementMetadataModel;
import org.bungeni.editor.selectors.SelectorDialogModes;
import org.bungeni.ooo.ooDocMetadata;
import org.bungeni.utils.BungeniFileSavePathFormat;
import org.bungeni.utils.CommonStringFunctions;

/**
 *
 * @author  undesa
 */
public class JudgementMetadata2 extends BaseEditorDocMetadataDialog {

    private static org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(JudgementMetadata2.class.getName());
    JudgementMetadataModel docMetaModel = new JudgementMetadataModel();
    registryQueryDialog2 rqs = null;
    
 //   OOComponentHelper ooDocument  = null;
 //   JFrame parentFrame = null;
 //    SelectorDialogModes dlgMode = null;
    
    
    public JudgementMetadata2(){
        super();
        initComponents();
    }
    
    @Override
    public void initialize() {
        super.initialize();
        
        this.docMetaModel.setup();
        initControls();
           if (theMode == SelectorDialogModes.TEXT_EDIT) {
            try {
                //retrieve metadata... and set in controls....
                docMetaModel.loadModel(ooDocument);
  
               String sJudgementNo = docMetaModel.getItem("BungeniJudgementNo");
                String sCaseNo = docMetaModel.getItem("BungeniCaseNo");
                String sJudgementDate = docMetaModel.getItem("BungeniJudgementDate");
                if (!CommonStringFunctions.emptyOrNull(sJudgementNo))
                    this.txtJudgementNo.setText(sJudgementNo);
                if (!CommonStringFunctions.emptyOrNull(sCaseNo))
                    this.txtCaseNo.setText(sCaseNo);
                 if (!CommonStringFunctions.emptyOrNull(sJudgementDate)) {
                    this.dt_judgement_date.setDate(sdfDateFormat.parse(sJudgementDate));
                }
                initJudgesTableModel();
            } catch (Exception ex) {
                log.error("initalize()  =  "  + ex.getMessage());
            }
         
        }
    }

    private void initJudgesTableModel(){
        String[] tableColumns = {"First Name", "Last Name", "URI" };
        this.tblJudges.setModel(new DefaultTableModel(tableColumns, 0));
        Vector tblModelVector = this.loadJudgesModelFromDocument();
    }
    
    
    public Component getPanelComponent() {
        return this;
    }
    
    private void initControls(){
        String popupDlgBackColor = BungeniEditorProperties.getEditorProperty("popupDialogBackColor");
        this.setBackground(Color.decode(popupDlgBackColor));
    }
    

public boolean applySelectedMetadata(BungeniFileSavePathFormat spf){
    boolean bState = false;
    try {
    String sJudgementNo = this.txtJudgementNo.getText();
    String sCaseNo = this.txtCaseNo.getText();
    Date dJudgementDate = this.dt_judgement_date.getDate();
    String sJudgementDate = this.sdfDateFormat.format(dJudgementDate);
    //get the assent date
       // docMetaModel.updateItem("BungeniParliamentID")
        docMetaModel.updateItem("BungeniJudgementNo", sJudgementNo);
        docMetaModel.updateItem("BungeniCaseNo", sCaseNo);
        docMetaModel.updateItem("BungeniJudgementDate", sJudgementDate);
        //this saves the judges listing in the table into the document
        this.saveJudgesMetadataToDocument();
        docMetaModel.saveModel(ooDocument);
    bState = true;
    } catch (Exception ex) {
        log.error("applySelectedMetadata : " + ex.getMessage());
        bState = false;
    } finally {
        return bState;
    }
}    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedJudges = new javax.swing.JTabbedPane();
        panelJudgementInfo = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtJudgementNo = new javax.swing.JTextField();
        lblBillName = new javax.swing.JLabel();
        txtCaseNo = new javax.swing.JTextField();
        lblBillName1 = new javax.swing.JLabel();
        dt_judgement_date = new org.jdesktop.swingx.JXDatePicker();
        panelJudges = new javax.swing.JPanel();
        scrollJudges = new javax.swing.JScrollPane();
        tblJudges = new javax.swing.JTable();
        btnAddJudge = new javax.swing.JButton();

        setBackground(java.awt.Color.lightGray);

        tabbedJudges.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N

        panelJudgementInfo.setBackground(java.awt.Color.lightGray);

        jLabel11.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        jLabel11.setText("Judgement No.");

        txtJudgementNo.setFont(new java.awt.Font("DejaVu Sans", 0, 10));

        lblBillName.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        lblBillName.setText("Case No.");

        txtCaseNo.setFont(new java.awt.Font("DejaVu Sans", 0, 10));

        lblBillName1.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        lblBillName1.setText("Judgement Date");

        dt_judgement_date.setFont(new java.awt.Font("DejaVu Sans", 0, 10));

        javax.swing.GroupLayout panelJudgementInfoLayout = new javax.swing.GroupLayout(panelJudgementInfo);
        panelJudgementInfo.setLayout(panelJudgementInfoLayout);
        panelJudgementInfoLayout.setHorizontalGroup(
            panelJudgementInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJudgementInfoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelJudgementInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBillName1)
                    .addGroup(panelJudgementInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(dt_judgement_date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblBillName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCaseNo)
                        .addComponent(txtJudgementNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        panelJudgementInfoLayout.setVerticalGroup(
            panelJudgementInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJudgementInfoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJudgementNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBillName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCaseNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lblBillName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dt_judgement_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        tabbedJudges.addTab("Judgement Info", panelJudgementInfo);

        panelJudges.setBackground(java.awt.Color.lightGray);

        tblJudges.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        tblJudges.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollJudges.setViewportView(tblJudges);

        btnAddJudge.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        btnAddJudge.setText("Add Judge");
        btnAddJudge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddJudgeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelJudgesLayout = new javax.swing.GroupLayout(panelJudges);
        panelJudges.setLayout(panelJudgesLayout);
        panelJudgesLayout.setHorizontalGroup(
            panelJudgesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJudgesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelJudgesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollJudges, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addComponent(btnAddJudge))
                .addContainerGap())
        );
        panelJudgesLayout.setVerticalGroup(
            panelJudgesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJudgesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddJudge)
                .addGap(3, 3, 3)
                .addComponent(scrollJudges, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        tabbedJudges.addTab("Judges", panelJudges);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedJudges, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(tabbedJudges, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void btnAddJudgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddJudgeActionPerformed
// TODO add your handling code here:
        rqs = new registryQueryDialog2("Select A Judge", "Select FIRST_NAME, LAST_NAME , URI from JUDGES order by LAST_NAME", parentFrame);
        rqs.setMultiSelect(true);
        rqs.show();
        Vector selectionData = rqs.getData();
        String[] selectionColumns = rqs.getDataColumns();
        Vector vColumns = new Vector(Arrays.asList(selectionColumns));
        Vector existingData = ((DefaultTableModel)this.tblJudges.getModel()).getDataVector();
        existingData.addAll(selectionData);
        ((DefaultTableModel)this.tblJudges.getModel()).setDataVector(existingData, vColumns);
       // this.tblJudges.setModel(arg0)
}//GEN-LAST:event_btnAddJudgeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddJudge;
    private org.jdesktop.swingx.JXDatePicker dt_judgement_date;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel lblBillName;
    private javax.swing.JLabel lblBillName1;
    private javax.swing.JPanel panelJudgementInfo;
    private javax.swing.JPanel panelJudges;
    private javax.swing.JScrollPane scrollJudges;
    private javax.swing.JTabbedPane tabbedJudges;
    private javax.swing.JTable tblJudges;
    private javax.swing.JTextField txtCaseNo;
    private javax.swing.JTextField txtJudgementNo;
    // End of variables declaration//GEN-END:variables


    @Override
    public Dimension getFrameSize() {
        int DIM_X = 229 ; int DIM_Y = 222 ;
        return new Dimension(DIM_X, DIM_Y + 10);
    }
    
    private int getColNoByName(String[] colArr, String colName) {
        for (int i = 0; i < colArr.length; i++) {
            String string = colArr[i];
            if (string.equals(colName)) {
                return i;
            }
        }
        return -1;
    }
    
    private String getValueByName(String[] colArr, Vector selRow, String colname) {
        int nColNo = getColNoByName(colArr, colname);
        if (nColNo == -1) return null;
        String foundValue = (String)selRow.elementAt(nColNo);
        return foundValue;
        
    }
    
    private void saveJudgesMetadataToDocument(){
        DefaultTableModel model = (DefaultTableModel)this.tblJudges.getModel();
        Vector vData = model.getDataVector();
        for (int i = 0; i < vData.size(); i++) {
            Vector rowData = (Vector) vData.elementAt(i);
            addMetadataVariable(rowData);
           // buildMetadataVariable()
        }
     
        //vector with first name, last name, uri
        
    }
   
    private static final String BUNGENI_JUDGE_META_PREFIX = "BungeniJudgeName:";
    private void addMetadataVariable(Vector rowData) {
        String firstName = (String) rowData.elementAt(0);
        String lastName = (String) rowData.elementAt(1);
        String uri = (String) rowData.elementAt(2);
        String metadataVariable = BUNGENI_JUDGE_META_PREFIX + uri;
        String metadataValue = firstName + "~" + lastName + "~" + uri;
        //add metadata variable to model
        docMetaModel.addItem(metadataVariable, metadataValue);
    }

    /**
     * This is a custom metadata model loader that loads all the Judgement related metadata
     * @return
     */
    private Vector loadJudgesModelFromDocument(){
        ArrayList<ooDocMetadataFieldSet> metaObjectByType = ooDocMetadata.getMetadataObjectsByType(ooDocument, BUNGENI_JUDGE_META_PREFIX.replaceAll(":", ""));
        Vector vTableModel = new Vector();
        for (Iterator<ooDocMetadataFieldSet> it = metaObjectByType.iterator(); it.hasNext();) {
            ooDocMetadataFieldSet docMetadataFieldSet = it.next();
            String metaName = docMetadataFieldSet.getMetadataName();
            String metaValue = docMetadataFieldSet.getMetadataValue();
            String[] judgeMetaValues = metaValue.split("~");
            Vector vRow = new Vector(Arrays.asList(judgeMetaValues));
            vTableModel.add(vRow);
            //add first name, last name , 
        }
        return vTableModel;
        
    }

   


}
