/*
 * referenceManager.java
 *
 * Created on July 14, 2008, 4:47 PM
 */

package org.bungeni.editor.panels.loadable.refmgr;

import com.l2fprod.common.swing.JTaskPaneGroup;
import java.awt.Component;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JFrame;
import org.bungeni.editor.panels.impl.BaseLaunchablePanel;
import org.bungeni.editor.panels.impl.ILaunchablePanel;
import org.bungeni.ooo.utils.CommonExceptionUtils;

/**
 *
 * @author  undesa
 */
public class referenceManager extends BaseLaunchablePanel {
    
    ArrayList<JTaskPaneGroup> paneGroups = new ArrayList<JTaskPaneGroup>(0);
    
    public final static String __TITLE__ = "Reference Manager";
    public final static Dimension FRAME_DIMENSION = new Dimension(498, 480);
    
    private static org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(referenceManager.class.getName());
    private String launchModeClass = "browseReferences";
    private final static String[] launchablePanelClasses = {
        "browseReferences",
        "brokenReferences",
        "externalReferences"
    };
    /** Creates new form referenceManager */
    public referenceManager() {
       // initComponents();
    }
    
    public void setLaunchMode(String launchMode) {
        this.launchModeClass = launchMode;
    }
    
    private void initPaneGroups(){
        try {
        for (String launchablePane : launchablePanelClasses) {
            
            JTaskPaneGroup jtpGrp = new JTaskPaneGroup();
            
            ILaunchablePanel panel = org.bungeni.editor.panels.factory.LaunchablePanelFactory.getPanelClass(launchablePane);
            panel.setOOComponentHandle(ooDocument);
            panel.setParentWindowHandle(parentFrame);
            panel.initUI();
            
            jtpGrp.add(panel.getObjectHandle());
            jtpGrp.setTitle(panel.getPanelTitle());
            this.taskPane.add(jtpGrp);
            paneGroups.add(jtpGrp);
            if (this.launchModeClass.equals(launchablePane)) {
                //expand this window
                jtpGrp.setExpanded(true);
            } else {
                jtpGrp.setExpanded(false);
            }
        
        }
        } catch (Exception ex) {
            log.error("initPaneGroups : " + ex.getMessage());
            log.error("initPaneGroups : " + CommonExceptionUtils.getStackTrace(ex));
        }
    }

    
    private void init() {
        initPaneGroups();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taskPane = new com.l2fprod.common.swing.JTaskPane();

        com.l2fprod.common.swing.PercentLayout percentLayout2 = new com.l2fprod.common.swing.PercentLayout();
        percentLayout2.setGap(14);
        percentLayout2.setOrientation(1);
        taskPane.setLayout(percentLayout2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taskPane, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taskPane, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.l2fprod.common.swing.JTaskPane taskPane;
    // End of variables declaration//GEN-END:variables
   
    public static void main (String[] args) {
            JFrame f  = new JFrame("Hello");
            f.add(new referenceManager());
                f.setAlwaysOnTop(true);
                f.setSize(new Dimension(498, 440));
               f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
               f.setVisible(true);
         
    }

    @Override
    public Component getObjectHandle() {
        return this;
    }

    @Override
    public void initUI() {
      initComponents();
      init();
    }

    @Override
    public String getPanelTitle() {
        return __TITLE__;
    }
}
