/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * panelSectionRefactor.java
 *
 * Created on Jan 30, 2009, 10:00:03 AM
 */

package org.bungeni.editor.section.refactor;

import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdom.Document;
import org.openoffice.odf.doc.OdfDocument;
import org.openoffice.odf.doc.OdfFileDom;
import org.w3c.dom.NodeList;

/**
 *
 * @author ashok
 */
public class panelSectionRefactor extends javax.swing.JPanel {
    String pathToFile = "";
    OdfDocument odfDocument = null;
    OdfFileDom contentDom = null;

    /** Creates new form panelSectionRefactor */
    public panelSectionRefactor() {
        initComponents();
    }

    public panelSectionRefactor(String fileName) {
        initComponents();
        this.pathToFile = fileName;
        loadDocument();
    }

    private void loadDocument() {
        try {
            odfDocument = OdfDocument.loadDocument(pathToFile);
            JDomOdfDomBridge jdofBridge = new JDomOdfDomBridge(odfDocument);
            //OdfFileDom fileDom = odfDocument.getContentDom();
            //build a JDom tree made of sections

        } catch (Exception ex) {
            Logger.getLogger(panelSectionRefactor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void buildJdomTree(OdfFileDom fileDom){
        //build root element

    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        treeSectionView = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSectionMeta = new javax.swing.JTable();
        btnCancel = new javax.swing.JButton();

        jScrollPane1.setViewportView(treeSectionView);

        tblSectionMeta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblSectionMeta);

        btnCancel.setText("Cancel");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 307, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(btnCancel)
                        .add(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 237, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 76, Short.MAX_VALUE)
                .add(btnCancel)
                .addContainerGap())
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblSectionMeta;
    private javax.swing.JTree treeSectionView;
    // End of variables declaration//GEN-END:variables

}
