/*
 * Copyright (C) 2012 UN/DESA Africa i-Parliaments Action Plan
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package org.bungeni.ext.integration.bungeniportal.panels;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultListModel;
import org.bungeni.ext.integration.bungeniportal.docimpl.BungeniListDocuments.BungeniListDocument;
import org.bungeni.extutils.MessageBox;
import org.bungeni.extutils.NotifyBox;
import org.bungeni.utils.BungeniDialog;

/**
 *
 * @author PC
 */
public class BungeniSelectDocumentPanel extends javax.swing.JPanel {

    BungeniListDocument selectedListDocument = null;
    BungeniDialog parentDialog = null;
    /**
     * Creates new form BungeniSelectDocument
     */
    private BungeniSelectDocumentPanel() {
        initComponents();
    }
    
    public BungeniSelectDocumentPanel(BungeniDialog parentDialog, List<BungeniListDocument> listDocuments) {
        this();
        this.parentDialog = parentDialog;
        init(listDocuments);
    }
    
    public BungeniListDocument getSelectedListDocument(){
        return this.selectedListDocument;
    }

    
    private void init( List<BungeniListDocument> listDocuments){
           DefaultListModel listModel = new DefaultListModel();
           for (BungeniListDocument bungeniSelectDocument : listDocuments) {
               listModel.addElement(bungeniSelectDocument);
           }
           this.listDocs.setModel(listModel);
           if (listModel.size() > 0 ) {
               this.listDocs.setSelectedIndex(0);
           }
            this.btnLoadDocument.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    selectedListDocument = (BungeniListDocument) listDocs.getSelectedValue();
                    if (null == selectedListDocument) {
                        NotifyBox.error("You need to select a document to import it !");
                    } else {
                        parentDialog.dispose();
                    }
                }
        });
        this.btnCancel.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                parentDialog.dispose();
            }
        });
        this.parentDialog.getRootPane().setDefaultButton(this.btnLoadDocument);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listDocs = new javax.swing.JList();
        lblDocSelect = new javax.swing.JLabel();
        btnLoadDocument = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        listDocs.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listDocs);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/bungeni/ext/integration/bungeniportal/panels/Bundle"); // NOI18N
        lblDocSelect.setText(bundle.getString("BungeniSelectDocumentPanel.lblDocSelect.text")); // NOI18N

        btnLoadDocument.setText(bundle.getString("BungeniSelectDocumentPanel.btnLoadDocument.text")); // NOI18N

        btnCancel.setText(bundle.getString("BungeniSelectDocumentPanel.btnCancel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblDocSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btnLoadDocument)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblDocSelect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnLoadDocument, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLoadDocument;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDocSelect;
    private javax.swing.JList listDocs;
    // End of variables declaration//GEN-END:variables
}
