SET CLUSTER '';
SET DEFAULT_TABLE_TYPE 0;
SET TRACE_MAX_FILE_SIZE 1;
SET WRITE_DELAY 500;
SET DEFAULT_LOCK_TIMEOUT 1000;
SET CACHE_SIZE 16384;
;
CREATE USER IF NOT EXISTS SA SALT 'c3459d68b885f882' HASH 'd7d9a1cd14b6fd5d090f41690066738f7e5de0aace6f763130953acd3204687f' ADMIN;
CREATE CACHED TABLE PUBLIC.DOCUMENT_TYPES(
    DOC_TYPE VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(100),
    TEMPLATE_PATH VARCHAR(250),
    METADATA_MODEL_EDITOR CHAR(100),
    METADATA_EDITOR_TITLE CHAR(50),
    WORK_URI CHAR(150),
    EXP_URI CHAR(150),
    FILE_NAME_SCHEME CHAR(150),
    STATE INT,
    UI_PROPERTIES CHAR(500) DEFAULT '' NOT NULL
);
-- 7 +/- SELECT COUNT(*) FROM PUBLIC.DOCUMENT_TYPES;
CREATE PRIMARY KEY PUBLIC.PRIMARY_KEY_265 ON PUBLIC.DOCUMENT_TYPES(DOC_TYPE);
CREATE CACHED TABLE PUBLIC.CONDITIONAL_OPERATORS(
    CONDITION_NAME CHAR(10) NOT NULL,
    CONDITION_SYNTAX CHAR(10) NOT NULL,
    CONDITION_CLASS VARCHAR(100) NOT NULL
);
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.CONDITIONAL_OPERATORS;
CREATE PRIMARY KEY PUBLIC.PRIMARY_KEY_8 ON PUBLIC.CONDITIONAL_OPERATORS(CONDITION_NAME);
CREATE CACHED TABLE PUBLIC.TOOLBAR_CONDITIONS(
    DOCTYPE VARCHAR(50) NOT NULL,
    CONDITION_NAME CHAR(20) NOT NULL,
    CONDITION_CLASS CHAR(100) NOT NULL
);
-- 29 +/- SELECT COUNT(*) FROM PUBLIC.TOOLBAR_CONDITIONS;
CREATE PRIMARY KEY PUBLIC.PRIMARY_KEY_1 ON PUBLIC.TOOLBAR_CONDITIONS(DOCTYPE, CONDITION_NAME);
CREATE CACHED TABLE PUBLIC.ACTION_SETTINGS(
    DOC_TYPE VARCHAR(100) NOT NULL,
    ACTION_NAME VARCHAR(100) NOT NULL,
    ACTION_ORDER INT NOT NULL,
    ACTION_STATE INT NOT NULL,
    ACTION_CLASS VARCHAR(200),
    ACTION_TYPE VARCHAR(50),
    ACTION_NAMING_CONVENTION VARCHAR(100),
    ACTION_NUMBERING_CONVENTION VARCHAR(50),
    ACTION_PARENT VARCHAR(50),
    ACTION_ICON VARCHAR(50),
    ACTION_DISPLAY_TEXT VARCHAR(100),
    ACTION_DIMENSION VARCHAR(50),
    ACTION_SECTION_TYPE CHAR(50),
    ACTION_EDIT_DLG_ALLOWED INT DEFAULT 0,
    ACTION_DIALOG_CLASS CHAR(100)
);
-- 66 +/- SELECT COUNT(*) FROM PUBLIC.ACTION_SETTINGS;
CREATE PRIMARY KEY PUBLIC.PRIMARY_KEY_4 ON PUBLIC.ACTION_SETTINGS(DOC_TYPE, ACTION_NAME);
CREATE INDEX PUBLIC.TAS_ACTIONPARENT_IDX ON PUBLIC.ACTION_SETTINGS(ACTION_PARENT);
CREATE INDEX PUBLIC.CONSTRAINT_INDEX_0 ON PUBLIC.ACTION_SETTINGS(ACTION_SECTION_TYPE);
CREATE CACHED TABLE PUBLIC.TOOLBAR_XML_CONFIG(
    DOC_TYPE VARCHAR(100) NOT NULL,
    TOOLBAR_XML VARCHAR(100) NOT NULL
);
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.TOOLBAR_XML_CONFIG;
CREATE PRIMARY KEY PUBLIC.PRIMARY_KEY_B ON PUBLIC.TOOLBAR_XML_CONFIG(DOC_TYPE);
CREATE CACHED TABLE PUBLIC.NUMBER_DECORATORS(
    DECORATOR_NAME CHAR(25) NOT NULL,
    DECORATOR_DESC CHAR(50) NOT NULL,
    DECORATOR_CLASS CHAR(100) NOT NULL
);
-- 6 +/- SELECT COUNT(*) FROM PUBLIC.NUMBER_DECORATORS;
CREATE PRIMARY KEY PUBLIC.PRIMARY_KEY_A9 ON PUBLIC.NUMBER_DECORATORS(DECORATOR_NAME);
CREATE CACHED TABLE PUBLIC.TRANSFORM_CONFIGURATIONS(
    DOC_TYPE VARCHAR(100) NOT NULL,
    CONFIG_NAME VARCHAR(100) NOT NULL,
    CONFIG_FILE VARCHAR(500) NOT NULL
);
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.TRANSFORM_CONFIGURATIONS;
CREATE PRIMARY KEY PUBLIC.PRIMARY_KEY_E ON PUBLIC.TRANSFORM_CONFIGURATIONS(DOC_TYPE, CONFIG_NAME);
CREATE CACHED TABLE PUBLIC.RESOURCE_MESSAGE_BUNDLES(
    BUNDLE_NAME CHAR(100) NOT NULL,
    DOC_TYPE CHAR(100) NOT NULL
);
-- 12 +/- SELECT COUNT(*) FROM PUBLIC.RESOURCE_MESSAGE_BUNDLES;
CREATE PRIMARY KEY PUBLIC.PRIMARY_KEY_EB ON PUBLIC.RESOURCE_MESSAGE_BUNDLES(DOC_TYPE, BUNDLE_NAME);
CREATE CACHED TABLE PUBLIC.GENERAL_EDITOR_PROPERTIES(
    PROPERTY_NAME CHAR(50) NOT NULL,
    PROPERTY_VALUE CHAR(500),
    PROPERTY_DESCRIPTION VARCHAR(100)
);
-- 42 +/- SELECT COUNT(*) FROM PUBLIC.GENERAL_EDITOR_PROPERTIES;
CREATE PRIMARY KEY PUBLIC.PRIMARY_KEY_E9 ON PUBLIC.GENERAL_EDITOR_PROPERTIES(PROPERTY_NAME);
CREATE CACHED TABLE PUBLIC.TRANSFORM_TARGETS(
    TARGET_NAME CHAR(100) NOT NULL,
    TARGET_DESC CHAR(100) NOT NULL,
    TARGET_EXT CHAR(100) NOT NULL,
    TARGET_CLASS CHAR(100) NOT NULL
);
ALTER TABLE PUBLIC.TRANSFORM_TARGETS ADD CONSTRAINT PUBLIC.CONSTRAINT_F PRIMARY KEY(TARGET_NAME);
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.TRANSFORM_TARGETS;
CREATE CACHED TABLE PUBLIC.DOCUMENT_METADATA(
    DOC_TYPE VARCHAR(100) NOT NULL,
    METADATA_NAME CHAR(50) NOT NULL,
    METADATA_DATATYPE CHAR(50) NOT NULL,
    METADATA_NAMESPACE CHAR(50),
    METADATA_TYPE CHAR(30),
    DISPLAY_ORDER INT,
    VISIBLE INT,
    DISPLAY_NAME CHAR(100),
    TABULAR_CONFIG CHAR(200)
);
-- 54 +/- SELECT COUNT(*) FROM PUBLIC.DOCUMENT_METADATA;
CREATE PRIMARY KEY PUBLIC.PRIMARY_KEY_FB ON PUBLIC.DOCUMENT_METADATA(DOC_TYPE, METADATA_NAME);
CREATE CACHED TABLE PUBLIC.EXTERNAL_PLUGINS(
    PLUGIN_NAME CHAR(100) NOT NULL,
    PLUGIN_LOADER CHAR(200) NOT NULL,
    PLUGIN_DESC CHAR(200) NOT NULL,
    PLUGIN_ENABLED CHAR(2) NOT NULL,
    PLUGIN_JAR CHAR(200) NOT NULL
);
ALTER TABLE PUBLIC.EXTERNAL_PLUGINS ADD CONSTRAINT PUBLIC.CONSTRAINT_90 PRIMARY KEY(PLUGIN_NAME, PLUGIN_JAR, PLUGIN_LOADER);
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.EXTERNAL_PLUGINS;
CREATE CACHED TABLE PUBLIC.METADATA_MODEL_EDITORS(
    DOC_TYPE CHAR(100) NOT NULL,
    METADATA_MODEL_EDITOR CHAR(255) NOT NULL,
    METADATA_EDITOR_TITLE CHAR(100) NOT NULL,
    ORDER_OF_LOADING INT NOT NULL
);
-- 7 +/- SELECT COUNT(*) FROM PUBLIC.METADATA_MODEL_EDITORS;
CREATE PRIMARY KEY PUBLIC.PRIMARY_KEY_39 ON PUBLIC.METADATA_MODEL_EDITORS(DOC_TYPE, METADATA_MODEL_EDITOR);
CREATE CACHED TABLE PUBLIC.DOCUMENT_SECTION_TYPES(
    DOC_TYPE VARCHAR(100) NOT NULL,
    SECTION_TYPE_NAME VARCHAR(50) NOT NULL,
    SECTION_NAME_PREFIX VARCHAR(100),
    SECTION_NUMBERING_STYLE CHAR(10),
    SECTION_BACKGROUND CHAR(255),
    SECTION_INDENT_LEFT CHAR(10),
    SECTION_INDENT_RIGHT CHAR(10),
    SECTION_VISIBILITY CHAR(10),
    NUMBERING_SCHEME CHAR(30),
    NUMBER_DECORATOR CHAR(20)
);
-- 48 +/- SELECT COUNT(*) FROM PUBLIC.DOCUMENT_SECTION_TYPES;
CREATE PRIMARY KEY PUBLIC.PRIMARY_KEY_F6 ON PUBLIC.DOCUMENT_SECTION_TYPES(DOC_TYPE, SECTION_TYPE_NAME);
CREATE CACHED TABLE PUBLIC.COUNTRY_CODES(
    COUNTRY_CODE CHAR(10) NOT NULL,
    COUNTRY_NAME CHAR(50) NOT NULL
);
ALTER TABLE PUBLIC.COUNTRY_CODES ADD CONSTRAINT PUBLIC.CONSTRAINT_A PRIMARY KEY(COUNTRY_CODE);
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.COUNTRY_CODES;
CREATE CACHED TABLE PUBLIC.LANGUAGE_CODES(
    LANG_CODE CHAR(10) NOT NULL,
    LANG_NAME CHAR(50) NOT NULL
);
ALTER TABLE PUBLIC.LANGUAGE_CODES ADD CONSTRAINT PUBLIC.CONSTRAINT_B PRIMARY KEY(LANG_CODE);
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.LANGUAGE_CODES;
CREATE CACHED TABLE PUBLIC.DOCUMENT_PART(
    DOC_TYPE VARCHAR(100) NOT NULL,
    DOC_PART CHAR(50) NOT NULL,
    PART_NAME CHAR(100) NOT NULL
);
ALTER TABLE PUBLIC.DOCUMENT_PART ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(DOC_TYPE, DOC_PART);
-- 8 +/- SELECT COUNT(*) FROM PUBLIC.DOCUMENT_PART;
CREATE CACHED TABLE PUBLIC.EDITOR_PANELS(
    DOCTYPE VARCHAR(100) NOT NULL,
    PANEL_TYPE VARCHAR(50) NOT NULL,
    PANEL_CLASS VARCHAR(100) NOT NULL,
    PANEL_LOAD_ORDER CHAR(2) NOT NULL,
    PANEL_TITLE VARCHAR(100) NOT NULL,
    PANEL_DESC VARCHAR(100),
    STATE INT,
    PANEL_NAME CHAR(20)
);
-- 21 +/- SELECT COUNT(*) FROM PUBLIC.EDITOR_PANELS;
CREATE PRIMARY KEY PUBLIC.PRIMARY_KEY_26 ON PUBLIC.EDITOR_PANELS(DOCTYPE, PANEL_TYPE, PANEL_CLASS);
CREATE CACHED TABLE PUBLIC.SELECTOR_DIALOGS(
    PARENT_DIALOG CHAR(200) NOT NULL,
    SELECTOR_DIALOG CHAR(200) NOT NULL,
    PROFILES CHAR(255)
);
ALTER TABLE PUBLIC.SELECTOR_DIALOGS ADD CONSTRAINT PUBLIC.CONSTRAINT_8A PRIMARY KEY(PARENT_DIALOG, SELECTOR_DIALOG);
-- 24 +/- SELECT COUNT(*) FROM PUBLIC.SELECTOR_DIALOGS;
CREATE CACHED TABLE PUBLIC.SUB_ACTION_SETTINGS(
    DOC_TYPE VARCHAR(100) NOT NULL,
    PARENT_ACTION_NAME VARCHAR(100) NOT NULL,
    SUB_ACTION_NAME VARCHAR(100) NOT NULL,
    SUB_ACTION_ORDER INT NOT NULL,
    SUB_ACTION_STATE INT NOT NULL,
    ACTION_TYPE VARCHAR(50),
    ACTION_DISPLAY_TEXT VARCHAR(100),
    ACTION_FIELDS VARCHAR(100),
    ACTION_CLASS VARCHAR(70),
    SYSTEM_CONTAINER VARCHAR(50),
    VALIDATOR_CLASS CHAR(100),
    ROUTER_CLASS VARCHAR(100),
    DIALOG_CLASS VARCHAR(100),
    COMMAND_CHAIN VARCHAR(100)
);
-- 107 +/- SELECT COUNT(*) FROM PUBLIC.SUB_ACTION_SETTINGS;
CREATE PRIMARY KEY PUBLIC.PRIMARY_KEY_C0 ON PUBLIC.SUB_ACTION_SETTINGS(DOC_TYPE, PARENT_ACTION_NAME, SUB_ACTION_NAME);
CREATE INDEX PUBLIC.SUBACTIONORDER_IDX ON PUBLIC.SUB_ACTION_SETTINGS(SUB_ACTION_ORDER);
CREATE CACHED TABLE PUBLIC.EDITOR_PROFILES(
    PROFILE_NAME CHAR(50) NOT NULL,
    PROFILE_DESC CHAR(200) NOT NULL
);
ALTER TABLE PUBLIC.EDITOR_PROFILES ADD CONSTRAINT PUBLIC.CONSTRAINT_E PRIMARY KEY(PROFILE_NAME);
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.EDITOR_PROFILES;
CREATE CACHED TABLE PUBLIC.EVENT_ONTOLOGIES(
    DOC_TYPE VARCHAR(100) NOT NULL,
    ONTOLOGY VARCHAR(255) NOT NULL,
    EVENT_NAME CHAR(100) NOT NULL,
    EVENT_DESC CHAR(200)
);
ALTER TABLE PUBLIC.EVENT_ONTOLOGIES ADD CONSTRAINT PUBLIC.CONSTRAINT_C PRIMARY KEY(DOC_TYPE, ONTOLOGY);
-- 9 +/- SELECT COUNT(*) FROM PUBLIC.EVENT_ONTOLOGIES;
ALTER TABLE PUBLIC.EDITOR_PANELS ADD CONSTRAINT PUBLIC.FK_EDITOR_PANELS_DOCTYPE FOREIGN KEY(DOCTYPE) REFERENCES PUBLIC.DOCUMENT_TYPES(DOC_TYPE) NOCHECK;
ALTER TABLE PUBLIC.EVENT_ONTOLOGIES ADD CONSTRAINT PUBLIC.CONSTRAINT_CE FOREIGN KEY(DOC_TYPE) REFERENCES PUBLIC.DOCUMENT_TYPES(DOC_TYPE) NOCHECK;
ALTER TABLE PUBLIC.EDITOR_PANELS ADD CONSTRAINT PUBLIC.CONSTRAINT_26 FOREIGN KEY(DOCTYPE) REFERENCES PUBLIC.DOCUMENT_TYPES(DOC_TYPE) NOCHECK;
ALTER TABLE PUBLIC.DOCUMENT_METADATA ADD CONSTRAINT PUBLIC.CONSTRAINT_FB FOREIGN KEY(DOC_TYPE) REFERENCES PUBLIC.DOCUMENT_TYPES(DOC_TYPE) NOCHECK;
ALTER TABLE PUBLIC.SUB_ACTION_SETTINGS ADD CONSTRAINT PUBLIC.CONSTRAINT_C0 FOREIGN KEY(DOC_TYPE) REFERENCES PUBLIC.DOCUMENT_TYPES(DOC_TYPE) NOCHECK;
ALTER TABLE PUBLIC.DOCUMENT_SECTION_TYPES ADD CONSTRAINT PUBLIC.CONSTRAINT_F6 FOREIGN KEY(DOC_TYPE) REFERENCES PUBLIC.DOCUMENT_TYPES(DOC_TYPE) NOCHECK;
ALTER TABLE PUBLIC.TOOLBAR_XML_CONFIG ADD CONSTRAINT PUBLIC.CONSTRAINT_B0 FOREIGN KEY(DOC_TYPE) REFERENCES PUBLIC.DOCUMENT_TYPES(DOC_TYPE) NOCHECK;
ALTER TABLE PUBLIC.DOCUMENT_SECTION_TYPES ADD CONSTRAINT PUBLIC.CONSTRAINT_2 FOREIGN KEY(DOC_TYPE) REFERENCES PUBLIC.DOCUMENT_TYPES(DOC_TYPE) NOCHECK;
ALTER TABLE PUBLIC.METADATA_MODEL_EDITORS ADD CONSTRAINT PUBLIC.CONSTRAINT_3 FOREIGN KEY(DOC_TYPE) REFERENCES PUBLIC.DOCUMENT_TYPES(DOC_TYPE) NOCHECK;
ALTER TABLE PUBLIC.SUB_ACTION_SETTINGS ADD CONSTRAINT PUBLIC.CONSTRAINT_10 FOREIGN KEY(DOC_TYPE, PARENT_ACTION_NAME) REFERENCES PUBLIC.ACTION_SETTINGS(DOC_TYPE, ACTION_NAME) NOCHECK;
ALTER TABLE PUBLIC.TOOLBAR_CONDITIONS ADD CONSTRAINT PUBLIC.TBC_FK_DOCTYPE FOREIGN KEY(DOCTYPE) REFERENCES PUBLIC.DOCUMENT_TYPES(DOC_TYPE) NOCHECK;
ALTER TABLE PUBLIC.TOOLBAR_XML_CONFIG ADD CONSTRAINT PUBLIC.CONSTRAINT_5 FOREIGN KEY(DOC_TYPE) REFERENCES PUBLIC.DOCUMENT_TYPES(DOC_TYPE) NOCHECK;
ALTER TABLE PUBLIC.TOOLBAR_CONDITIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_15 FOREIGN KEY(DOCTYPE) REFERENCES PUBLIC.DOCUMENT_TYPES(DOC_TYPE) NOCHECK;
ALTER TABLE PUBLIC.DOCUMENT_METADATA ADD CONSTRAINT PUBLIC.CONSTRAINT_9 FOREIGN KEY(DOC_TYPE) REFERENCES PUBLIC.DOCUMENT_TYPES(DOC_TYPE) NOCHECK;
ALTER TABLE PUBLIC.RESOURCE_MESSAGE_BUNDLES ADD CONSTRAINT PUBLIC.CONSTRAINT_EB FOREIGN KEY(DOC_TYPE) REFERENCES PUBLIC.DOCUMENT_TYPES(DOC_TYPE) NOCHECK;
ALTER TABLE PUBLIC.TRANSFORM_CONFIGURATIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_EA FOREIGN KEY(DOC_TYPE) REFERENCES PUBLIC.DOCUMENT_TYPES(DOC_TYPE) NOCHECK;
ALTER TABLE PUBLIC.ACTION_SETTINGS ADD CONSTRAINT PUBLIC.CONSTRAINT_0 FOREIGN KEY(DOC_TYPE) REFERENCES PUBLIC.DOCUMENT_TYPES(DOC_TYPE) NOCHECK;
ALTER TABLE PUBLIC.DOCUMENT_PART ADD CONSTRAINT PUBLIC.CONSTRAINT_1A FOREIGN KEY(DOC_TYPE) REFERENCES PUBLIC.DOCUMENT_TYPES(DOC_TYPE) NOCHECK;
ALTER TABLE PUBLIC.SUB_ACTION_SETTINGS ADD CONSTRAINT PUBLIC.CONSTRAINT_C08 FOREIGN KEY(DOC_TYPE, PARENT_ACTION_NAME) REFERENCES PUBLIC.ACTION_SETTINGS(DOC_TYPE, ACTION_NAME) NOCHECK;        