SET TRACE_LEVEL_FILE 1;       
SET WRITE_DELAY 500;          
SET CLUSTER '';               
SET DEFAULT_TABLE_TYPE 0;     
SET DEFAULT_LOCK_TIMEOUT 1000;
SET TRACE_LEVEL_SYSTEM_OUT 0; 
SET CACHE_SIZE 16384;         
;             
CREATE USER IF NOT EXISTS SA SALT '639c4703c5386f70' HASH '8a14c49558709d0202b9712aa71bd64dee9494450b6b3a06f89e409ac7ae0bae' ADMIN;           
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_113DAF61_DFF7_4070_A19A_8CEBEBC694F7 START WITH 3 BELONGS_TO_TABLE;    
CREATE CACHED TABLE PUBLIC.METADATA_SOURCES(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_113DAF61_DFF7_4070_A19A_8CEBEBC694F7) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_113DAF61_DFF7_4070_A19A_8CEBEBC694F7,
    DISPLAY_NAME VARCHAR(100),
    TABLE_NAME VARCHAR(100)
);     
-- 2 = SELECT COUNT(*) FROM PUBLIC.METADATA_SOURCES;          
CREATE PRIMARY KEY ON PUBLIC.METADATA_SOURCES(ID);            
CREATE CACHED TABLE PUBLIC.EDITOR_MACROS(
    PROG_LANGUAGE CHAR(20) NOT NULL,
    LIBRARY_NAME VARCHAR(100) NOT NULL,
    MACRO_NAME VARCHAR(100) NOT NULL,
    NO_OF_PARAMS INT
);          
-- 23 = SELECT COUNT(*) FROM PUBLIC.EDITOR_MACROS;            
CREATE PRIMARY KEY ON PUBLIC.EDITOR_MACROS(PROG_LANGUAGE, LIBRARY_NAME, MACRO_NAME);          
CREATE CACHED TABLE PUBLIC.ACTION_PARENT(
    DOC_TYPE VARCHAR(100) NOT NULL,
    ACTION_NAME VARCHAR(100) NOT NULL,
    PARENT_ACTION VARCHAR(100) NOT NULL
);               
-- 18 = SELECT COUNT(*) FROM PUBLIC.ACTION_PARENT;            
CREATE PRIMARY KEY ON PUBLIC.ACTION_PARENT(DOC_TYPE, ACTION_NAME, PARENT_ACTION);             
CREATE INDEX PUBLIC.CONSTRAINT_5_INDEX_0 ON PUBLIC.ACTION_PARENT(ACTION_NAME);
CREATE CACHED TABLE PUBLIC.DOCUMENT_SECTION_TYPES(
    DOC_TYPE VARCHAR(100) NOT NULL,
    SECTION_TYPE_NAME VARCHAR(50) NOT NULL
);          
-- 13 = SELECT COUNT(*) FROM PUBLIC.DOCUMENT_SECTION_TYPES;   
CREATE PRIMARY KEY ON PUBLIC.DOCUMENT_SECTION_TYPES(DOC_TYPE, SECTION_TYPE_NAME);             
CREATE CACHED TABLE PUBLIC.DOCUMENT_TYPES(
    DOC_TYPE VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(100)
);
-- 5 = SELECT COUNT(*) FROM PUBLIC.DOCUMENT_TYPES;            
CREATE PRIMARY KEY ON PUBLIC.DOCUMENT_TYPES(DOC_TYPE);        
CREATE CACHED TABLE PUBLIC.GENERAL_EDITOR_PROPERTIES(
    PROPERTY_NAME CHAR(50) NOT NULL,
    PROPERTY_VALUE CHAR(50),
    PROPERTY_DESCRIPTION VARCHAR(100)
);              
-- 13 = SELECT COUNT(*) FROM PUBLIC.GENERAL_EDITOR_PROPERTIES;
CREATE PRIMARY KEY ON PUBLIC.GENERAL_EDITOR_PROPERTIES(PROPERTY_NAME);        
CREATE CACHED TABLE PUBLIC.DOCUMENT_METADATA(
    DOC_TYPE VARCHAR(100) NOT NULL,
    METADATA_NAME CHAR(50) NOT NULL,
    METADATA_DATATYPE CHAR(50) NOT NULL,
    METADATA_NAMESPACE CHAR(50),
    METADATA_TYPE CHAR(30),
    DISPLAY_ORDER INT,
    VISIBLE INT,
    DISPLAY_NAME CHAR(100)
);            
-- 5 = SELECT COUNT(*) FROM PUBLIC.DOCUMENT_METADATA;         
CREATE PRIMARY KEY ON PUBLIC.DOCUMENT_METADATA(DOC_TYPE, METADATA_NAME);      
CREATE CACHED TABLE PUBLIC.FORM_COMMAND_CHAIN(
    FORM_NAME VARCHAR(100) NOT NULL,
    FORM_MODE VARCHAR(50) NOT NULL,
    COMMAND_CATALOG VARCHAR(100) NOT NULL,
    COMMAND_CHAIN VARCHAR(100) NOT NULL
); 
-- 10 = SELECT COUNT(*) FROM PUBLIC.FORM_COMMAND_CHAIN;       
CREATE PRIMARY KEY ON PUBLIC.FORM_COMMAND_CHAIN(FORM_NAME, FORM_MODE);        
CREATE CACHED TABLE PUBLIC.FORM_CATALOG_SOURCE(
    FORM_NAME VARCHAR(100) NOT NULL,
    CATALOG_SOURCE VARCHAR(255) NOT NULL
);              
-- 4 = SELECT COUNT(*) FROM PUBLIC.FORM_CATALOG_SOURCE;       
CREATE PRIMARY KEY ON PUBLIC.FORM_CATALOG_SOURCE(FORM_NAME);  
CREATE CACHED TABLE PUBLIC.LOCALIZED_DISPLAY_STRINGS(
    STRING_KEY VARCHAR(50) NOT NULL,
    LANG_CODE VARCHAR(2) NOT NULL,
    DISPLAY_STRING VARCHAR(255) NOT NULL
);     
-- 1 = SELECT COUNT(*) FROM PUBLIC.LOCALIZED_DISPLAY_STRINGS; 
CREATE PRIMARY KEY ON PUBLIC.LOCALIZED_DISPLAY_STRINGS(STRING_KEY, LANG_CODE);
CREATE CACHED TABLE PUBLIC.TOOLBAR_MENU_GROUPS(
    GROUP_NAME VARCHAR(50) NOT NULL,
    DISPLAY_STRING_KEY VARCHAR(50) NOT NULL
);           
-- 1 = SELECT COUNT(*) FROM PUBLIC.TOOLBAR_MENU_GROUPS;       
CREATE PRIMARY KEY ON PUBLIC.TOOLBAR_MENU_GROUPS(GROUP_NAME); 
CREATE CACHED TABLE PUBLIC.TOOLBAR_MENU_ACTION_BLOCKS(
    BLOCK_NAME VARCHAR(50) NOT NULL,
    STRING_KEY VARCHAR(50) NOT NULL,
    ACTION_MODE VARCHAR(50) NOT NULL,
    TARGET VARCHAR(100) NOT NULL
);    
-- 0 = SELECT COUNT(*) FROM PUBLIC.TOOLBAR_MENU_ACTION_BLOCKS;
CREATE PRIMARY KEY ON PUBLIC.TOOLBAR_MENU_ACTION_BLOCKS(BLOCK_NAME);          
CREATE CACHED TABLE PUBLIC.CONDITIONAL_OPERATORS(
    CONDITION_NAME CHAR(10) NOT NULL,
    CONDITION_SYNTAX CHAR(10) NOT NULL,
    CONDITION_CLASS VARCHAR(100) NOT NULL
);  
-- 2 = SELECT COUNT(*) FROM PUBLIC.CONDITIONAL_OPERATORS;     
CREATE PRIMARY KEY ON PUBLIC.CONDITIONAL_OPERATORS(CONDITION_NAME);           
CREATE CACHED TABLE PUBLIC.TOOLBAR_CONDITIONS(
    DOCTYPE VARCHAR(50) NOT NULL,
    CONDITION_NAME CHAR(20) NOT NULL,
    CONDITION_CLASS CHAR(100) NOT NULL
);              
-- 8 = SELECT COUNT(*) FROM PUBLIC.TOOLBAR_CONDITIONS;        
CREATE PRIMARY KEY ON PUBLIC.TOOLBAR_CONDITIONS(DOCTYPE, CONDITION_NAME);     
CREATE CACHED TABLE PUBLIC.SUB_ACTION_SETTINGS(
    DOC_TYPE VARCHAR(100) NOT NULL,
    PARENT_ACTION_NAME VARCHAR(100) NOT NULL,
    SUB_ACTION_NAME VARCHAR(100) NOT NULL,
    SUB_ACTION_ORDER INT NOT NULL,
    SUB_ACTION_STATE INT NOT NULL,
    ACTION_TYPE VARCHAR(50),
    ACTION_DISPLAY_TEXT VARCHAR(100),
    ACTION_FIELDS VARCHAR(100),
    ACTION_CLASS VARCHAR(70),
    SYSTEM_CONTAINER VARCHAR(50),
    VALIDATOR_CLASS CHAR(100),
    ROUTER_CLASS VARCHAR(100),
    DIALOG_CLASS VARCHAR(100),
    COMMAND_CHAIN VARCHAR(100)
);          
-- 10 = SELECT COUNT(*) FROM PUBLIC.SUB_ACTION_SETTINGS;      
CREATE PRIMARY KEY ON PUBLIC.SUB_ACTION_SETTINGS(DOC_TYPE, PARENT_ACTION_NAME, SUB_ACTION_NAME);              
CREATE INDEX PUBLIC.SUBACTIONORDER_IDX ON PUBLIC.SUB_ACTION_SETTINGS(SUB_ACTION_ORDER);       
CREATE CACHED TABLE PUBLIC.DIALOG_CLASSES(
    DIALOG_CLASS CHAR(100) NOT NULL
);             
-- 3 = SELECT COUNT(*) FROM PUBLIC.DIALOG_CLASSES;            
CREATE PRIMARY KEY ON PUBLIC.DIALOG_CLASSES(DIALOG_CLASS);    
CREATE CACHED TABLE PUBLIC.ACTION_SETTINGS(
    DOC_TYPE VARCHAR(100) NOT NULL,
    ACTION_NAME VARCHAR(100) NOT NULL,
    ACTION_ORDER INT NOT NULL,
    ACTION_STATE INT NOT NULL,
    ACTION_CLASS VARCHAR(200),
    ACTION_TYPE VARCHAR(50),
    ACTION_NAMING_CONVENTION VARCHAR(100),
    ACTION_NUMBERING_CONVENTION VARCHAR(50),
    ACTION_PARENT VARCHAR(50),
    ACTION_ICON VARCHAR(50),
    ACTION_DISPLAY_TEXT VARCHAR(100),
    ACTION_DIMENSION VARCHAR(50),
    ACTION_SECTION_TYPE CHAR(50),
    ACTION_EDIT_DLG_ALLOWED INT DEFAULT 0,
    ACTION_DIALOG_CLASS CHAR(100)
);
-- 17 = SELECT COUNT(*) FROM PUBLIC.ACTION_SETTINGS;          
CREATE PRIMARY KEY ON PUBLIC.ACTION_SETTINGS(DOC_TYPE, ACTION_NAME);          
CREATE INDEX PUBLIC.TAS_ACTIONPARENT_IDX ON PUBLIC.ACTION_SETTINGS(ACTION_PARENT);            
CREATE INDEX PUBLIC.CONSTRAINT_INDEX_0 ON PUBLIC.ACTION_SETTINGS(ACTION_SECTION_TYPE);        
CREATE UNIQUE INDEX PUBLIC.CONSTRAINT_INDEX_3 ON PUBLIC.ACTION_SETTINGS(ACTION_NAME);         
CREATE CACHED TABLE PUBLIC.ACTION_MODES(
    DOC_TYPE VARCHAR(100) NOT NULL,
    ACTION_NAME VARCHAR(100) NOT NULL,
    ACTION_MODE VARCHAR(20) NOT NULL,
    MODE_HIDDEN_FIELD VARCHAR(100) NOT NULL,
    SUB_ACTION_NAME CHAR(50) NOT NULL
);               
-- 15 = SELECT COUNT(*) FROM PUBLIC.ACTION_MODES;             
CREATE PRIMARY KEY ON PUBLIC.ACTION_MODES(DOC_TYPE, ACTION_NAME, ACTION_MODE, MODE_HIDDEN_FIELD, SUB_ACTION_NAME);            
ALTER TABLE PUBLIC.ACTION_PARENT ADD CONSTRAINT PUBLIC.CONSTRAINT_3 FOREIGN KEY(DOC_TYPE) REFERENCES PUBLIC.DOCUMENT_TYPES(DOC_TYPE);         
ALTER TABLE PUBLIC.ACTION_SETTINGS ADD CONSTRAINT PUBLIC.CONSTRAINT_1 FOREIGN KEY(ACTION_SECTION_TYPE) REFERENCES PUBLIC.DOCUMENT_SECTION_TYPES(SECTION_TYPE_NAME);           
ALTER TABLE PUBLIC.SUB_ACTION_SETTINGS ADD CONSTRAINT PUBLIC.CONSTRAINT_10 FOREIGN KEY(DOC_TYPE, PARENT_ACTION_NAME) REFERENCES PUBLIC.ACTION_SETTINGS(DOC_TYPE, ACTION_NAME);
ALTER TABLE PUBLIC.ACTION_PARENT ADD CONSTRAINT PUBLIC.CONSTRAINT_4 FOREIGN KEY(DOC_TYPE) REFERENCES PUBLIC.DOCUMENT_TYPES(DOC_TYPE);         
ALTER TABLE PUBLIC.DOCUMENT_SECTION_TYPES ADD CONSTRAINT PUBLIC.CONSTRAINT_2 FOREIGN KEY(DOC_TYPE) REFERENCES PUBLIC.DOCUMENT_TYPES(DOC_TYPE);
ALTER TABLE PUBLIC.ACTION_PARENT ADD CONSTRAINT PUBLIC.CONSTRAINT_7 FOREIGN KEY(DOC_TYPE, ACTION_NAME) REFERENCES PUBLIC.ACTION_SETTINGS(DOC_TYPE, ACTION_NAME);              
ALTER TABLE PUBLIC.ACTION_SETTINGS ADD CONSTRAINT PUBLIC.CONSTRAINT_0 FOREIGN KEY(DOC_TYPE) REFERENCES PUBLIC.DOCUMENT_TYPES(DOC_TYPE);       
ALTER TABLE PUBLIC.TOOLBAR_MENU_GROUPS ADD CONSTRAINT PUBLIC.CONSTRAINT_11 FOREIGN KEY(DISPLAY_STRING_KEY) REFERENCES PUBLIC.LOCALIZED_DISPLAY_STRINGS(STRING_KEY);           
ALTER TABLE PUBLIC.DOCUMENT_METADATA ADD CONSTRAINT PUBLIC.CONSTRAINT_9 FOREIGN KEY(DOC_TYPE) REFERENCES PUBLIC.DOCUMENT_TYPES(DOC_TYPE);     
